package sparkswood;

import java.util.Arrays;
import java.util.List;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.HBaseConfiguration;
import org.apache.hadoop.hbase.MasterNotRunningException;
import org.apache.hadoop.hbase.client.HBaseAdmin;
import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.io.ImmutableBytesWritable;
import org.apache.hadoop.hbase.mapreduce.TableInputFormat;
import org.apache.hadoop.hbase.util.Bytes;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.function.PairFunction;

import scala.Tuple2;


public class Baba {

    public static void main(final String[] args) {

        final String[] pans = {
                "f1unqJQ0r/ThsYHmrZldO5Mhnyt9Xq6WZQOMemPUVJyofw==",
                "f/3JOpMp93vURgeNp2YbkwkiMSV8pJHvQynLeLUHnDTNfw==",
                "f3mHbEDX/A2w4SFRDCIz4m20y0lmwcR4H19TjAVtwNBmfw==",
                "f8I5+r7ZDlosMaCNgs7L/vA5b9VwNwWor7PbvCerBGrbfw==",
                "fxpd/t8RMkcfGyB+XQA07ompw0hOZEiXZkMaJUIscOQ+fw==",
                "f4c/zg2ftaOrrKoC/LKQQSDh4dwzUmYAsItHLAl2hBlEfw==",
                "f6c7465DU04uoi8NNgnUH2qdx/misYd1O1dICdFbvPkAfw==",
                "fyvvC0/d3EthhdD/flkTY7N2f6Z8kvRWoIuMm6s6DV4kfw==",
                "f+DVkHKgTDQD+IyE/EJgOuGnvUv3Jc3p2VX00DCOauSpfw==",
                "f76L+QA55OW2YC6fhKZiOXBjqha1pk3TeF9hV7xdnnBBfw==",
                "fxtLpJjzh8bSLjAhCclqtFNi1y+tkFPB0PfaSvDt6KDRfw==",
                "f6ICT7NDiYJTLiRFZB+6b38vieNokiY+5w3qyiH3IVE0fw==",
                "f7Q/wmccy8AT9ojvVcPmsgYqOGl9f7ej8aI7NbJNPrFFfw==",
                "f8uFtcyoZz8MOT0hN/wXqf+cFn2z9/6dWZbrNfgCqhZhfw==",
                "f9Fx+tATC8ft5QNreo+UHjINSzn2zGwVU3ASFKGPAOP0fw==",
                "fwcIyVKWjz4bKbVlE1r4Hk2r1VFYHV0xUPjSyrQAeuvAfw==",
                "fxVCL74W9U94l4lyfea0xiOZs4YMm5xdlpOk6Tw6DWzTfw==",
                "fz1pzNja8nfn3BCUwIwFYylOzPgrsRgeJD3w1PU69n90fw==",
                "f5Rtcgmzzgb2y6XSUJOxSzaOJQVOI99b9D4i7z/DiC1Jfw==",
                "f/EMiOF/9MuredRjh1Yb+QHolXD4Ai52ARn5uiEtzzNCfw==",
                "fyjcsB2FjKBCamPrwQ8Sr85GQtxiopFzsPWPzJow+7twfw==",
                "fy+PBt/onhAHrzpjk9DelLkqYii7q+aJiRcolgi+2Y4xfw==",
                "fwhBDRUbcG8m1coA+S9hQ/MO0ieS8bKUeYy1OC2z5K2Afw==",
                "f82dCp5E9F0U7j2M8htT7shIC7V44wxgOVB8kdrMZ41Cfw==",
                "f7NcSCRcCHY/bUC1rCy0YtngqmPsi5tXWHXu30M7Zvkifw==",
                "f3tmDnO9aYCL3iLbvOxpDUWF+4P+3jEHjvlZTfdVV/5tfw==",
                "fxy3+BnAO0ax0kfK7mYl0WJMMSdBAaHX4EqOPKB/JWUZfw==",
                "f41bEi77uF/pfu16Aqz4RtcOb46brME0lxgxXWhRRiEhfw==",
                "fywRU5oFMTe6/N12J7efahYqN7nxgSzJCgVXaTatd0Vyfw==",
                "fztwEoTe7TZxYRe68lzr1R+JBDHkOA8nszjSZ3uWWuWafw==",
                "f3vViuTqFoYJyxY2+ykhv0Xk1oVQ3CvXpWCzk5OwhpKSfw==",
                "f4iQEAkLyWXrnGRfttD2ahkN8V5n5duczcsWz6FtCNU8fw==",
                "f/LddrcWeR9Q7R+Eyua1fFhDptl01lnsnqPicQKBABJtfw==",
                "f9ef4dRHM5kgsHLatraWnJ9DSwC5UgN+u7U90yBfsihRfw==",
                "f+BZUHUN6NJpN6JfvEY5cnKs/dQmO5PbwG7Kis67r49ifw==",
                "f3BjOhC8HQn5MrSUKUhaZ2nhz49cfzTXcfir0xLOT5Srfw==",
                "f01VvbQO5gI7RL2O5TqRxuzqIjyl69qBM+LQlB85D27Jfw==",
                "f/URiApagIvkK/9VF80zsPClYb5H26jTFLjt1fceFpTifw==",
                "f0iP6ic00p0FXuFnHFeL3t6/9dsFV5tGdOgH7youfo93fw==",
                "f2eIuUvSnx5uOYt0aqPJjSNFdidkaR722f7mAJnhfaYPfw==",
                "f7AJ4j7acFMp5Bets4d3BnznMan2Xa/n2AnfYLl6SprOfw==",
                "f+dGZF2eMl2MLWJHRHqnxG/Y+DtUWNjWhZyBZ7+YoXQlfw==",
                "f9cbPvLCLhHUYcNyepBOkOEQJL+QtKjTo2l9ZlC82GTbfw==",
                "f9xeC8HVY/m4o/XtFce1/dIwNV6Vzb146WyysEkModx5fw==",
                "f7iUIyPzCVRFTlrOaClD+eXh/Z35eW3NinOlgXd9FQxhfw==",
                "f5HjynzHBfTlP4bmoi8XVelLal1Lmfggj9+a891MGkmDfw==",
                "f0/Rtcl3LzMtSsIOOnKYj4+dnGhlMYfhNMG+pqPFE5PDfw==",
                "fwgheEVG09P3v8w3Zn0kTGgLfn8d7UZl5Ho/z11CeoMMfw==",
                "f4fgxGhnOs4BAJpilK888ce0FayKeHzxss02UkpzAMNrfw==",
                "f8qXsQvbIe3l/XC1j6ucVlFV6WV1kMLXjgGr60DNd3fRfw==",
                "fyWTwqFQDf7Gng+cfT83Ozz2gBDtM2k2VyrBxwS7fTBLfw==",
                "f7sH0iuGiHAmUcLLGoFcJG4aS24LfOBpdX9gertvjwCWfw==",
                "f+K0MfIbSjIjIIS2zRpTdX5N6SdeZoP7UZZLsKKEkm/7fw==",
                "f41VsYiI1ijkoe5ncs7vez4VOeNJngvsrq2uy0lA/mrQfw==",
                "fwBOGUCGQCpINLuWMzFb3hQnxIAB5WSSLJKAhX69lCfYfw==",
                "f1FvP+QmPhJiATtvb6XPCA3DLipMU5oVuWqHh7j2o8rafw==",
                "f4tmkRmLOhhQbY9+QCOBY5J3izwY9tFQJd8P6Gn6Ck/Sfw==",
                "f7byd8GVShLDf+CNbWqgUV/RJAOTfq4tyELx4xoHZdtwfw==",
                "f95Hazen+a+jfYkna/D1cSXZmkoi9kj9cNvdLpH4PU4Efw==",
                "fx9nv3+T9JFMY1rdWSzZmklcA/lDNqWogt6+m3QovnqIfw==",
                "f47J+52K8maWpZL69w1TCfaEPyym3cSIvt74SAdcxmH/fw==",
                "f1Ev+WzWcJLNX3OpQTmEb2RqBbDyGPeBenMpWIHzVNmofw==",
                "f5pktj0uf3K1jsTDGe3ocxOJmkKBYnOrHG4Tnt8Crs3Afw==",
                "f3cD7VxEAWCtfIoI/4YgWE82fKJWSomKMQ7RC7CEF6pzfw==",
                "f5DI4WKL3XyBWEDfr0t5NNx3RD+iDmvY356odjt/rWAJfw==",
                "f4VZIupe5gfu/JZ+OqEbvB48loYF+DdO7tlfEDeET+W9fw==",
                "f6kTUAlbHu2JRx4Enbt14u/5IPegfpYB7LJkX/ho5tfufw==",
                "f5iR8s8CUypGieu9uYty4cM8Gs8P0Cmcm9NLEtdoQm2lfw==",
                "fy1OOMiMEdXGLAu+ofvHNcr3Z4WbAYFR/m/3guyWk0F6fw==",
                "fwWQ5IdSuYsgqN6RYijqwkETU5Ny2c5i52cWgXxW1/BHfw==",
                "f7hex9gVBPjUett3b2bJ/+BE40WT38M2W8zBJmwoW/lkfw==",
                "f3IJEPO6ZrXhOxyLnBOoIKgsxjA5qlSbCrFArXMIDRsZfw==",
                "f7B2KRzBLrwtDXV0tvq3G6X3Ms35u8utnt9AFtWWA52Efw==",
                "f+SBZPD5cljvnbfHVXP6nk7k8qwwrjJtB1BBVQaygvo6fw==",
                "fy6ZUe6yv71mvJ0KjQFCsxFXfMlBXALobEnRMrb/C8Rcfw==",
                "fyoF0ZQfqLU3YHtx7TXcY+1YvwAK5IEDSgozESWoYcbRfw==",
                "f22+2XdOlkV/fH3U4OVNWInzVr37/utlUsnMWPwN+8JHfw==",
                "f2Ac82VeqM3aC8+XQn4kX+PGZ2REg5iBfnhYT4DICNW1fw==",
                "f+cipYMtIxSS2jhd2T2V84Ajm2eXvXW9y5cHeO8QG3lMfw==",
                "f8t/ZtOpaHB8PI+3K7B6/kVZOhIwzLNszZpsRH6LPXv0fw==",
                "f32gOh+GzZhYXiSjOU8U21l5exwToPer6IUYFQGfI+i9fw==",
                "f9HyjDh1mep9qrTL4QrFjnLn4HdVcDWdMnqFqg7KS/Zifw==",
                "f2vApB6zG4NXQosTCRbAvmWqk07pbppSn7C7o7JXobPTfw==",
                "fy5YXMkqSps+F2grfm4+lXgQpfr41q65H1cUrXXPrSIPfw==",
                "f0cnQHzB5CndU5M6058cdLgdE5nrIwU4PeBKvBVphuknfw==",
                "f8jyXqRxx+jnHFTSyUgn8vLda7T93iv8DUIWPhPK20Wofw==",
                "f/dxLjNBK5/qgMD1jqzbj+bMn3e8CK+KaORyufs0skPKfw==",
                "fz9JR/A899DvD87SjJp2nHz/fcpoTPb6CjouYMom/ooWfw==",
                "f3iiFhFcIgeyRyl3KC1tT/ggoFVT96kAfE018uH/4vY1fw==",
                "f+4G5X339euhhFrdEzWlPKijMurimqxwEJzbwLQv6Wl6fw==",
                "f2zADTlwd+EzRoMmZaWiIka/p1A1OCY/j0k7odZcNFpvfw==",
                "f3V33paX3dGy+F54bEvqMmA7XPDR79snEaN7VQwgf7pnfw==",
                "f/3Vz+YF8D4PFBmQkbvwxQ7LD6k5M5SCcFeMckibq1nofw==",
                "fwsvVqjVK+TW4WscOTufx8i6+OnuxRQ3287xfrAX1ldtfw==",
                "fw8hdMWU3BMdh3SNKXm8/SUXTdc+pJSi0WAQ10ka9v/Lfw==",
                "f0WXEyCNtbWKawqOXmwNQXJFS3wsyIGwQI2ettzzNLdifw==",
                "f4zuNMZZn8ThzTxcMmPwgp4L8z7m4ChGio9WBezQ9W3vfw==",
                "fzcSr6o08p0As5zrwbZ5talHhIxxr0LHnACv8jiMJCpOfw==",
                "f+Nsx3M9P4QHzYenqaIY1NCgcVDjo3syCP5TAI8SBC28fw==",
                "f7Q7AXLV35wR2a+HojUbcDaCU2GEdW7cpWbuqmYG7hnxfw==",
                "f1vAC4wGulDFl3QHuuuX6q83f18piT5gIlFffo8T44qNfw==",
                "f/AwBLsPmL9DgrycVA5RLBfsz0fI+PNkZC4Od5NAiCFqfw==",
                "f+rIqsIW9e5hcP+OdrcF+GGxDZbAasCdrtb25wUef6w2fw==",
                "f3NQav5Cba9x3IXb7LtnCeHGP3i10VCdoCpKcVi7h5Rqfw==",
                "fxGf4HbjQE79fKSz38FVP7FgWsgD/l3niALzAeRzLj6ffw==",
                "f+378cJMZBYEjKOUNJ7auM4a72lEKfE1T9rz9XJ4cKmZfw==",
                "f6TdPj8ovidrlmoWJvUK1JQR0+d1o5g7Y14fxMGs9dSEfw==",
                "f4ij9N642grxedueTwSOZ6NyVcxRsj7+DH1KmdiDL6dDfw==",
                "f0+H2UEu1tqLosH0t10H7bt26fcB50mJCL2lbSnitRsDfw==",
                "fyOgv8uqw+c32ZgdYmql1YNJnq+tvBYRzx2LAinbPJaSfw==",
                "fz8eyC536l/Dxb8e6+zSYJGWnIP7PeM7bQwwKjlJG4+Gfw==",
                "f5OH14txIlgDImAWZ+aydqMo8TGRylCKNUSK80c5uN5dfw==",
                "f58NC7knKjZRuDXcJzoJN96Ukpla7mA/yh/1m0FOnaqbfw==",
                "f8TGmZGNOWJ6RSQMiU4bdrv6nTf5TXnV7t+cKskwwugXfw==",
                "f9H406zB9DtUqAVMfNqRn+NzxWL3lapjUP8TD9uNH4pXfw==",
                "f1DJPvDoMYJyGQSCAscCOTh/2qsbiID11sYB1784saoofw==",
                "f/xIGSQSWpUFz9z+AIrFzjOHSKLmlnM+dcfK9UGUZxWYfw==",
                "f5AzUA0DAgbxMAOK58yQdIkAnR8xoZmrZAIo2eb7Tjbifw==",
                "f8QrBaN02krnO72PmQK2KYdrHDA7imxoEadkY0jV285mfw==",
                "f8EOSmr+bW/3SG7P6vLaWEiufTIZ8vzH9sIFN+anSLZ+fw==",
                "f0Pc9h4MeRpMpsFxlsU/yM0zBGy381l21wpaSvSk6sxvfw==",
                "f25CEYRz0tM/rTWswLAoJCz0HW8l8FN2hlrROA2Phawwfw==",
                "f5+5gFeEGv1oyhfbdfi6pQAAyvDlEhtMW8JZavj0+CRqfw==",
                "fyprNQBcGZ+C/ZrNda56vSE96BS7H84x6y3TroPenQu7fw==",
                "f7apziQVSH0nMzelCgKLqwi87W8QShqocKGl+clMFQ2Afw==",
                "f1iG/ozhH30Zr4jg3WnAeTtMOfB923FyjoqXqHG320Ryfw==",
                "f4IRRnl4AEF2QtSKCmLhLKS8p6lsVFWEUmsIyyjSDsQPfw==",
                "f1/c5K8qpz9ZGDUHBonpcppddgKlkYXtem51VlBiVI4mfw==",
                "fzSAYbJfDrjwhrfwbNC1/o7zlGlqIT6aI0c4p3a4j+EFfw==",
                "f3MAeHMjY04EsBQLtnNpN3lcwEtqAh9LD6CaIradZGrjfw==",
                "f00Ds6KdXrlVCX1Fc+8Anqd0j6UbaHN2S3QNrMhvxsOpfw==",
                "fzMyu6g/WbZ3wr9nsGyonRQ3Y+ltEuvun7iPJfLZM+fffw==",
                "fwDoLmWVuBFCZ30MDIJ4PSctN1FwxncpbgFNYW8Ne9jKfw==",
                "f/BF38IDNZIpY68GF33n/D161VVTW6jpJc/anfBl5qlVfw==",
                "f9iPt0teiS1Xq80lvAVwpeBZzNT2LHmZ2KmXmP2iLtsIfw==",
                "f14FMMlpptBshDDDTsGZNWC6Y8mC082iaOqMHs9lEGHqfw==",
                "f2CG7zEeCKKPT2uXRorl9exkt1Tom/FVaVAaAbFBmYyDfw==",
                "f8UsGn7UI1lSBRhyweJyJbCRVGPFTBBToX4tk+w8krBjfw==",
                "f66zhhmKFqIbKK2jWIvzrenQAOPJiie4KVqKV1o++yr7fw==",
                "f4iTGZ2mSBwQv2CxQknOONDeYuRvkOB7SY/tV4fdwdPHfw==",
                "fzLdS0KUSP8z7M+22rZVZuc2oJ28LRPPAv2aKhDLB8cyfw==",
                "f5iK8vVwrrGitdF/bstKzUMSLLMEobCjAkeCgPhLOJyZfw==",
                "fxeKUK3S2eclWlbHbyYUVsf7CYkftRiQFzYoJOXi8zvIfw==",
                "f8WXZjAWiJtbPW6XstrmTtEXcgo5itFRTX835Meau0iofw==",
                "f/9AEqhQ+Vb8fmDxilUCtE3uw8oh6pm8sINA147Xxqqsfw==",
                "f3viJhu6nruQEk/y2X+mdFdrP/dqoauesKOICrGnLXFEfw==",
                "f4VBMRtt27dEPpLHMCN7iLRjWk0J5KtVF/HanwaHH8Scfw==",
                "fyhS1IcqdXu0JT3H6WPVFS9ZPyxm0sLFUPo5CpheI781fw==",
                "f55J4U8AHvqaEPGutcvjQstdfEBdxVTex64lljmT2cLRfw==",
                "f4BHGCXpYxTHFGFWjKS5aZ0ixLiKvogE8trDWi2uOyaUfw==",
                "f2N7zVJ022LOJa9x2N2Us3SWN89qwdtOW5WhxT7/baHXfw==",
                "f3C5gY/oajR1+rGvqEuWV1Trgy4GmT8GEyEOQ6+3YYQdfw==",
                "f+SBxIDxC/rvk5tFxqFkqoB9eTFi2VN0deP/bABrhExgfw==",
                "fwX/XoobzoxRC9haNh2rnznZfb9eag2LphrIV0z4aFG0fw==",
                "f+jRVjMXEEVt1JEKGal9stYFJiXRuVfPQ8peHRAkWuIXfw==",
                "fwrHmwmlDBFCfUYcgVIkAxdI9W9Kq+pnTygf6qPM9RTWfw==",
                "fy2FsNuG5rVfeg4+iQUbigeh4OekoXYz1Kc2mskA98p3fw==",
                "fzSHssJl3N1rEHa2ctBcy8s584Vz8X5/8BFoJgWe3dw1fw==",
                "f6Ie7GzuxKmWIaXuHCF3R3JnpcSsSirkAZwoTeeWx/4Dfw==",
                "f9V+BHvuuFYeq8brVQ3Ss5BJjvhdedikvkytwZ9Q6gZZfw==",
                "f1u9Ls4RebutJW6F3JufXHFdRTtjXlg84nUDngi8YH5ifw==",
                "f18vgXORuGaswNlwXx1ES+oBq14OGW+q/4ON0MWzaJQHfw==",
                "f5qrh5d6KTfEnTBZmUILJ9MhS3EvA3JAmND5tDC7uidPfw==",
                "f1yKd1apnckxD0ui2CPhH8FQLOhjrwE+z1uxAVEevrkxfw==",
                "f7Pvbt7Kpwjx+HQgDMG415/WgXDaxRfhoOClKUfmjkDRfw==",
                "f9isZzq0bg17XAJbXreu89fGUmUKcBUoESs8URYxOQvPfw==",
                "f0f2a97WA0p0AwxlcV46Wmws5j9EYMquplxQrSMgSrWefw==",
                "fxKmKvJ4GZwqKdWiNO2XiT6N+/sHRvQfQsO76QyPMX7Qfw==",
                "fw/f+tDdD56Fd546XlttTz8uFTL9CJDgtAuoDLBG1OxSfw==",
                "fx9k8i6LvBibCGedB9WFbe2m1N13QFsRGQYX0jCSxTFKfw==",
                "f+03tKAqBiPZxIIdON7k2+RIjUEQErHmyY1Ejo19Preofw==",
                "fwaF1gLo44gsWU/76fhUv1ABnbV4wjbdCzAIqIof0R8zfw==",
                "f8wd0bYjv9D1q38n4cf+19pLiuszd8QT4px1gPwpH/Kmfw==",
                "f+6CfaMtjkMhnTbJiXMfTJcmuPMzO0STE3pWG/gqt5TJfw==",
                "fy+Vl2yz+EiB+0YCyaxP00nFma9gVf/BvBobcSXPSN1Ffw==",
                "f1VKDDYl9+U758FDNtQFCr37GiKTfNFnSINYr44OKJZufw==",
                "f+euw3FNL8spzNQfpO8Hz5qQRq3pLe27VNYd07YWHLZ6fw==",
                "f1XKGIvdKiYe3uI/ftMoG+2WwO1jjw247oaZ1LgrYHz3fw==",
                "f7b5ygGSZ23mhFjY/AuWr8IGrR8Gzyxm/nat4csRSMfCfw==",
                "f6JM0vpZgHEVBcQNsQ4tk96IVtlzeCmuXwI3hhnAR8qXfw==",
                "f/ALltPGdIXsVa2ft308a3tJ4JkIFFTE2GA1VxwqpaKhfw==",
                "f5dv5pWGOQsK0G2b7dAlbq6IKmK6Z3hw8litdM8Heioefw==",
                "f9suhIwX9yOIxpPxWVTK3O7PCgjm0brd4UvGrYjExPaVfw==",
                "f4WKEAKewxLl6tAN+7s9Qm7jL5ambi3/+xWHtlB+igdSfw==",
                "f4rnzhCZAAJVi2q1cDFRSBZxUsHbsChZU5nW1nY52o5jfw==",
                "f7J0Berd7obmHaHp4aFpccdGGiG6E4IicWq/gSKfiKMefw==",
                "f7SC1TD01EU949mYpU3QjkTJZBU5Ywnj/m6d3gcAw2Axfw==",
                "f/MevybZF5SD6ghytaIx+eH5s4ofUWyQ+wo8Y2Qk+EwAfw==",
                "f8GZyoopvL4c+HNyvcvFEHdCksvs72jUCj62Ied2o55+fw==",
                "f2v/yEFUKxbeIUAVCdiWt40WXUXk1iN136XRZGZRZzXkfw==",
                "f8hA3CZ/6QaDIfvKw4sXpT/JEy0khG4gNR8eFDxGCykEfw==",
                "f6unuthMDPllIiQFj1aCX6a6GeDM0DqXbWZCdz5m1X1Wfw==",
                "fxOB64+DhEWNGHzixYZ61W8brqvS4EWSB4h4B2Ss3Dcofw==",
                "f66jOaHOdioKlQ37ogI4uYOuuyhD0t2BrIw9ECl87cbHfw==",
                "fyiacs44sSB7p/RV3ecb/iQhHVhLH8oKwvRPPXC89mxzfw==",
                "f77tj4qeq8cNQo67xScVpx2SzBktJXYR9GJmgYB6fjOVfw==",
                "f741zHB1sP4Yrfbq1oqGHvyWDE/zdpWm7TWZwp1wFIE0fw==",
                "f8pGFIbLhUr94+pvapyuqyVi3cPfyNTjeKQlLAkYQbrvfw==",
                "f94lrFObg+/YFjMIPR+NkXsL9OhN9OqKlN63IiHJQs2Afw==",
                "fyAU2hWa/Nw9rrsxg2Yf6IXEaHXibDZHLrppbLgFPkiFfw==",
                "fz6bupGNtPok/MIzeSus4VJPNIO7N/XsZcACNZKpdZTvfw==",
                "f6SVuXbqd6T/vH2iVGDJxanBflq7/Oy6NGMoStWXPaR2fw==",
                "f12u9YZs9aizv7vVggTdWVmgYfSl0owLyaUCgo7iYDe0fw==",
                "f2TQ32o7KUhsDlqHQUDsCGlLlIUme0FMmr7ZW+F+RLJjfw==",
                "f2D+LNY023t1JiH/H0wM80x6pFwz+nAsPMJ1EqD8ppbrfw==",
                "fy+Z8//ZSB5uNxBQKvwKc/UyrCOYvl8qydqynYjDgsVffw==",
                "fzpOh9OqXzu8jT5bdy8jU/OB0PmAg4ltTPZEjfFOg1NWfw==",
                "f5AQhdoazVsUkve4vkrE9f0JCKUrokBTuN0iwtWBAYTZfw==",
                "f0j1tGYEu8glO6kP2q9/PtY95PxQyzIO1MNbCSqerLLhfw==",
                "f3USaHjQrl9yO3ALgqzSme5Hg9Pi7yNtiTpkmNJUrumVfw==",
                "f6m1HD18t933PT2PJA1lfd+OZcNhH1BR1BrGUrvnH5Xifw==",
                "fxYJeVlFVAX0kfkd2anbCKFus8cOLS5O2SLnzvfj7Dfxfw==",
                "f4XFl/0+1e3oICcaCzBWeSNRnFdxOlQnPN7yaYwktkQAfw==",
                "fwjQ80zlOguK/iWqtPARxx2IPVR65DnObMupOUuKUEeRfw==",
                "fy/Pf8v4bmO8ZteTDrKnAKFl+D09cN7lAIuoH/yFAU37fw==",
                "f6lGfP9M/oxSdPlaYLpdOeF689k9ra/Rd1JiXOyKgWYRfw==",
                "f5omLZD7MgXSJS2iFTUERb2/RQEdBnM82vUTkPMEAcsvfw==",
                "f1Qz1uzFiO9p8FXmamrBsrApbUppqZBle4E1GerHshsafw==",
                "fx006JMpsHTUvoW883zScP49gskpFSbuCYhsOLDcqHhWfw==",
                "f0EI8vojHtj4U4rlG5p0Sil2+7e8hzRUpC7ObOjIM5Zmfw==",
                "f0M3ghiFRKJdMmhTqs19jeDi/NAKVLMa3SqGsOENp9D/fw==",
                "f54CaP21AsA/kMAv/qAh7WVUyZPRP7RddbmAkWaFX/o3fw==",
                "fzBq8Ocj/sRQzEqGxnFngjIhV/+Vjsa5QFa6gKPog9WLfw==",
                "f+7kD3OUDyXHvm8isXqj55v5AYNPbmqQsOgybvVnLODvfw==",
                "f7s51w7fkSX83gQbRpFx9iOFvVL0SqpE9aol16OrsL8zfw==",
                "f37YTBCGcgjEig2vNmSc98hFDecEDDkk+Pu41NEsDB4Pfw==",
                "fyX1idfTAAViIlPkB8dWLMuOl+au5YyVE20e4RkG2F0cfw==",
                "f/wPyTE1eYkYod7D3Pv6uWOZ2K7OYOXQouLjWdlLuE0Zfw==",
                "f1mSINhB2Yx9TwZrKkEXYsHDwEZH1LArfVrvFCjgv7OWfw==",
                "f2FIfjR7eaZiHp5fpuWQKNm/hdLXBwPtELJTDzz8km9cfw==",
                "f1H7NflzXFgwAGaFaU7sbB6hi4t5U4BX+/wy7hOIB7IGfw==",
                "f29rElwjdtpYgLhNNANoM7jzuuhKqMc2c996v4nUGq1dfw==",
                "f8y51Ks8C/PSPFqimjjIvt9wtpeAiYmGCwsXbhwTPI2Efw==",
                "f2tp7LLRwnw5OnoVLKF+dYsDoeRoRpHMRL+aufNqnXJUfw==",
                "f9HOKtgGHMVqDQZlPtm1Ubb+djCCXxke2RiU+9bsLJRDfw==",
                "fx7MdOeD22m+V5OjZle0bzicRtFWQc12XBRtSczTecXKfw==",
                "f6M/+roW4/dVqfD5B+MmwK0YkwmBJNiRJdZEzdW3F2dqfw==",
                "f1dIn5Sz3H0Gm1q2omSXpgyVgUyxsmqtQH07lCusPhndfw==",
                "f/WE/ckLthHz1M1Me90ZujBrOS/X2tXlXQaATepBgUzyfw==",
                "f8fRnvqGDlIPsMxR4qr3SFyn8Tf368177uf+d5Lbcvqdfw==",
                "f3Ak2DqgfbMkrFR0fXZxMSCJdcHlGlWGdn9xizGvfg0gfw==",
                "fwgV+hoCTo7bAGmuXiaEd/xpmZL43LJNif7B1/jZGuOtfw==",
                "f5cJA1eF0DTWR84Ynecf7GPJ5k3Dq3gJGsIlH7IjYhccfw==",
                "f2jarzrmvyDXT/twZFb2AEJpoRNcEqqoGJ4fOe6cjmGHfw==",
                "f17xWYXehZln9MvpBPcKmaCPBDdS4ql35Fz//KKJIeZkfw==",
                "f50r31mJnoXeDYfLgImhED9x2t++DWl1ZaIm2tc7lD7sfw==",
                "f0LSmSVhcQCsaEL3bB/fO90ZDRXsZPluxKtdW+TVf4LQfw==",
                "f98Qz4Cpvg2aVayAJeRB0u3kQGbCFPO3Wn5mTPSiP0mFfw==",
                "fxW5ezTbQzc7uS5VBj4j/xptyiDxfotkgJzt3v3j9w0Efw==",
                "fxU710A7j5HPjsW/n8bWHxrQ3/z6GYIU60OfxARgmZUFfw==",
                "f6rwjepriRphmehle+vibHw0/AJGi0/FG2t4ndAhqWfhfw==",
                "f55b/awXWRQqFE+goCGeg0qwohoeeeLOd1b4mYpvQCoJfw==",
                "f3OqhH7UllWOGAJnLDAQuIqGjZzJJYozOOmGhLR7C7qefw==",
                "fz+QoTe23vYNhXOdfRz6lqXVzIy0NmXPx2D82KijN+X6fw==",
                "f/kByH3vCwwy5pN3Ug8Cpv6+OieAmlwPazTwQq/rVGh5fw==",
                "f74b26FJyX70qXho/0Sj30VoQvDvVY0IImEHlf+0kVEBfw==",
                "f1+X9w0Mht2yWohy9em9GSCImopeqVIhk0gze1qJl4/Dfw==",
                "f/TbABg72+0FTyGe08+0XBYqma0CZFXZpL9XrU0kVoIafw==",
                "f92y65diQlD6uMZGYz6ScxfUWUn+BVmvEF/tdpx/agurfw==",
                "fxasWlX/ZCgjrissH8Zmy64NcnhDLck0ENsEPfZDKsT0fw==",
                "fxxLelAXZRui4nAu8T2bS0BXangKuUXtNgugVNaPBBrZfw==",
                "f/4EHLNO6EvqIE8f0dpooVE3PdgoxZTzB2rnsLicqJw8fw==",
                "f4cXSnE0VnBTlytgAOQCSXv5lnHT1PbcGtM/cMBPKuvAfw==",
                "f97VcrQc/w31g5Cp9wQpIHMHi3wwGNxlwRaru3f3SaS8fw==",
                "f0zS4dGedUsQJQgkgP0X57IJzmVInPfg1QC0paVCZzzAfw==",
                "f808qOjiIbCnCgiOm9wkvcl/DuGH68HJoiAfZh7IKb66fw==",
                "f9s8xamW9Y7j3iLc69zOjKWclY1tgjDpcaVsHAfrYZVUfw==",
                "fyUaUSIz8+z5KU4cyBBh++HqtyE9VRBc5BBa0lotsrqvfw==",
                "f1OTHrj5n4Ebv9T9ufk8s8NX6zxl6cL33GLKgjzQjAuufw==",
                "f79iQN8fnTH7CGgyhuwh7A5CppUy8UqV+WRjN384aLK9fw==",
                "f0djBCIK+1lFxdfyHtmClrguQ39wIJFXckjI8GSaAmbLfw==",
                "f0vsAy4MzTaTUM0SAHA/58KGo3c1wbFeSdfJ4lGjSi3Rfw==",
                "f++C9bC5dnwSZyDh+0BzWfrKJGLQ3T0xHPOCB4wi6+a5fw==",
                "f15wZ+8ousP2uShhJADbbQ3CHKj/l+UEk076cu46H1r2fw==",
                "f2KhR7j7YfRYO5rtAcHwgFIjWjQDwjVQ9JzL5Cmt7+cDfw==",
                "fx2zhtqyAo6lZ4ME4US4JeGeIqCpksdNO5avHnFxtmTMfw==",
                "f1ApgM2QjhnBw+BevCez1e1VzcGam0ipUYg55n20M/1efw==",
                "f8TtP7/fpWJTJZdxpGz167fpSL8nCcaJVCXdvK3lUUNTfw==",
                "fwQHm0hR1m08saXomOEQNW91ShSHLXx5OL1rQ8GlWQuhfw==",
                "f+eLQctLED8OdzfD/dZ6hu1L6gSNnLeTx/YwgU7F0zxYfw==",
                "f2s3/P70GHuTjAPm+dq2DC+/fV3Stvvj2jox7nvt1Ilkfw==",
                "f+UBk6PoDsot/yLkpm5wMrQP4UbpjvqVD9EH13vsJwbGfw==",
                "f3FQ2Z7HxtLMFSJt6jMXJnnhsZU58/wP5tkJ46OXEtbzfw==",
                "f5VOqopQERag7hXbA7Er4eLxPQeLoN2U4qjJMPrvZaHefw==",
                "f7AJifeC5U29p2dztcBhz1U/+hdLn6mk65N61ES4zPAUfw==",
                "f/r/kfdWqbG0Tl59nwwr5MDwW/wZbz1ZOX6wtSv8BM4Efw==",
                "f8hHzM3qGQfu7/LVtnbFzILQk8kaVizwAcsh6s4isJbzfw==",
                "f7m3+eOC5S1k+JO/p27lprstQDNPn7QwMEyfmtxP4iSFfw==",
                "fz/Teah+mrl2+EPEeIVSvlwG6+kxyhMUFODFS/g9/MGcfw==",
                "f9Zu3jQSOUbKKyORlMxmn5d72Zoj8+aOMuViH2TncJ+6fw==",
                "f+ub8HI4MGWMR8qRIkMDtCbtdb0Qy/pbzB0UDat0LoaMfw==",
                "f8E7MlsZZVVfPbSik7EC/rCj58fOqP/MeGDnCHWYh0Jrfw==",
                "f+JK9Kl0yQbxCG+sTqbBKDoRJW/8wsPnwITT9lNF5lt8fw==",
                "f4lnoxyT5HEzxdkSpsJQqxI+8lx6QL1sn4E9Ncf8hg3Xfw==",
                "f3bl+EHzPkQPS9ECnY3wRYKmDwcB7u5eVoFpR3g/VXqrfw==",
                "f2eeZf52W7sBZeiVCdl8I8gw1ge6uOyMw7bolzrxBSvofw==",
                "f6y0v1T1+4y7ucVH8WCKIykArMw5o31QrCMQxwQ7OpDMfw==",
                "fwyfj/p9RNmwgwWU/ubcrEFC6GdVc5l5NLjRGeOS/178fw==",
                "fwCS4z3x+Jezjrf24ZsJhuGCDfQCWTOWqv3h9gQgKBqJfw==",
                "f11uubSyrRk6EpTGBPBnMMJQdoL3eN4mVH0Y3ok+Xnulfw==",
                "f7EBYCjTO2CnGMSKAJnVYng30ASehAs/fi5Ghfs2j493fw==",
                "f4JLgXN8xQutZwxM15dYmaJi0Y/AMrdyghNtTiCfolVsfw==",
                "fzwM9jr8dKH9lnwiGSs8/+/vEbjc0YKOvyyQFYhyEx9Sfw==",
                "f4CDTKJ7d0i+PX417rfhwoWn+Za3dfWaoNzgSvbgS6pQfw==",
                "f7CRin+2bJZxz1ILW2MvUJ56Qda3gV7ONvswh1IHdGerfw==",
                "f0eCL/YJDwvtCv9C1uqEYW0icb7KXAyXzgHUZzWiaO48fw==",
                "f6Ow+YKEfcTq73YaFytvNbthZGU8fLNuLD1T5KJz7Eeqfw==",
                "f2+FsIKfQFWuVlcATrrWs4j84t9DNaP59AQfcOo/IU4Bfw==",
                "f4spWsuXInNSVW8eWdhzpYU3yNpNOlQt8nhIq/UEwqX7fw==",
                "fylQVan5soYsgUsO/utRrOXJog1jvzfIo9/4NPYA61xKfw==",
                "f53K4/cNR+z6jOSrdd4SXaoRYmtnNfdms0M/51UaZqjwfw==",
                "fyYdc2MvfGygyfdiyDlavCk3uFIuCvjl3GqhWRcmrJ00fw==",
                "f7+S9yiWFQ5g2MqGU8/WnZCc9zIFWvsErvG5VrN88phPfw==",
                "f33V8jGzEDx6I7+RKlHTFRVF82cntgElgNlgn2efpIc1fw==",
                "fwN3mdRUvQZ7/0pVK6Yw/M98yiWG060Qbi2Hp9o1y/nqfw==",
                "f5BI4L6cN+PBWR8yAgf3a96E5Mqe9SxWbBejrdKAGYQkfw==",
                "fxeTuQTVDg6ebbxfp8fT39FK5+9C0wvhT1zb0oo4PKMyfw==",
                "f8uF9DlxIuqS3V+XUDV7HujS2whX4z+GDzCd8Oj8xI52fw==",
                "fxBlZ9dlRpvlOzmjYpqUwGQydMisO86QoE8nzhXDbrQTfw==",
                "fzHglZE+4MjSfnWCw26Pl1oZy5gh4tJe9RJtDVTsrYr8fw==",
                "fy7RPsL3v64nGBF0qFnIu08O3kcz21qsqLzDq5TNEdOUfw==",
                "f68KydnAIxeO8DkluhWad4VkbdXOSu5fi3IjffSMiL2ifw==",
                "fzlZM92ow2BvtoBM7zr6DKa1Dec8uQtitRzGk+JuNsKHfw==",
                "f9yIaOFGq5C6H2LpQtAQkA+ZK64dS7CSGXyvBfz0hT7Xfw==",
                "f4Bh7dk70FX94YtQh4N1YOCzL4IIJrRfcYXcS1HzuKK6fw==",
                "f8RSGIn0hn7IgHwwmn3qBZPH3Eh8tfDAz4+CBUDDwoOZfw==",
                "f7x2m+VMd0MZjvVGFKJRmsQUrzjHpIvN4ej0/9zGlqYRfw==",
                "fxeSo1CpNWZdiZfzpKulpxcM74X7nupzG+19JS4fkhGhfw==",
                "f0I1nZOSlPvpkhqhPYfIh/STgX9A039GYCcV9eeEYP2Ofw==",
                "f2b+RgxG1UiLLcfzp11ipHOf1qFtEnoubIcZEY0s+uxAfw==",
                "f+Uj/hQjX2FFa9ESt5C2aOX8LV8hfWFT79a1KmS5g3Kxfw==",
                "fymG6Dq+A17obSuqhOin2of3iRxPNouvGxRzGyAlbPUvfw==",
                "f+AfJpZ1sjjwLI+5yIfTs6WBaK+OGlUyTSWYdGjHXvBofw==",
                "f1Fs5HuENrAjxp+hQfMjGOgfw42kxwsEglBuxPXIvwT3fw==",
                "f/+2097Au2wJxNQOgX98LxLe2Qc1fjR5no2HU4rhhZskfw==",
                "f3fnUaDjVFTJckB0//1mcs8coHYSImdztsJxJ3th1NeCfw==",
                "f2uHfDIEL3Z3HPSZFdYO8TmN5sNAPzxRalQMpv/ty+Z6fw==",
                "f9m2SAEYJxBN/8V0mg6QSANtTbUO3Xd9rKz8/7amojh8fw==",
                "fzDRgrjTXsmLa0AVEB1t11LqV66Bb1XHAD3wN2j17NAofw==",
                "f0spwYZLxexVX7XxoeMv9gCQaEndiAwZA63rGfm9WCxmfw==",
                "f7La2xWiH+Net1fwV8NZlMGzuCUfbUNph/2dpwHPp+OLfw==",
                "fzYyEZcvJpGa5AoWfI3YAlyIzkX6FOAycc8FC+lGa+eufw==",
                "f/In+hxbOa4DR/noT6ZjP8zg2qa4S5w67LBNaufW5pegfw==",
                "fw5Nr8t7qhF7DgEdOKMTplHl2lG8wert+gM0Pw+h8uFEfw==",
                "f84kfDcEsFQX0lZk019KNMVFpuasqRJQMykKP/EGHoGLfw==",
                "f1Ev3cRBHxPVfa+w/2EHqUMC8Zy26cgHQFWrrHge/yiLfw==",
                "f2fLGrflta7CiJSFZnuV5SnUhvgeaCL9TSM6VcHp3Z7Bfw==",
                "f3tUrQi2cGn3VG9eirhavCPBlP3JUPne7klXQng2L11hfw==",
                "f4kX3c09VzFtVuXoZ1Tz7sby6Jk8L+T+YbnUCUQj9EVWfw==",
                "f7KjnVdvSSyxr3HMuY3yEW/YpoTTTBzsYna2XeJzsD/8fw==",
                "f0wKolK2E1i2bg/IlAo4CeIzeAv7gCiSNXifVsex+Bg+fw==",
                "f3ySp/S/k69Nq1IeZcMJ2lHlqUIYxUUejGQ5UwcjyQH/fw==",
                "f9+HjWaD3Uzrazhqgok1bJ87kdSTtm0HeZg4doEIritafw==",
                "fyR78cXv9fWQY6NZjSvlDiPhvIQWP2rtrt+l69Ym31ncfw==",
                "f1biVPrpow12hVVTK362Rq5LNluEuI4dxiHEp9Pt6VRPfw==",
                "f8yfXLzhPgVAutRXrUbnsNR58SW67fZLYJxwQ7xRF8jefw==",
                "f6TZfEGZAelvpMG2ZNO1EhTP7fq8hStxxhPysc0pYWlHfw==",
                "fyvqobSUVEj3mUcqIlLYenNSAZBSrTryJbVz2q4sHw6Mfw==",
                "f/MpTKdzT6uOIaLejg1+PbkuAQlu6U7Ks/RKFtaVu4oIfw==",
                "f45vffQsoYPHC8eEv5vl4HPePrs3m4COKyn5Xxgzk0iIfw==",
                "f6cYi/9ksAyLZVJkGdHVyVgI003/xlhoTWlUHmGtL5KTfw==",
                "f9y2QC5ZJoIx7zmG9krMXZ84CdjE9ewxkxoU5RHBdkVxfw==",
                "f2QKR/31RPE0ILVtliqIGgvz2r1+7tiFbF4be5BTGbhifw==",
                "f7w02M36LUW2FzxFF/CLaQu1D5Q0zIRIOH0vhPY9GdjLfw==",
                "f94Xg7+g+iPvssT3VE03Wzwh1Yc9Z9DFP+3ur6LUXCqpfw==",
                "f7Phe57EO59sOHZ4Jp+kq6LwXeeLc2YJZWYNhj5YYpJifw==",
                "f65PERzhrbYo62MOJS9KXHpaDJ64lRVQmH3Oag0+686cfw==",
                "fxXs2YVc5GnjHzfBtFruNvTlA6ALSjufow9y6YIc3eVHfw==",
                "f53N5Fc7CRfvSGhCSNckEMgMXIc1ppWSnMByfcL1hZbKfw==",
                "f831FF5bjpQU4nt+0g0Fw9ccEtkK4KZccUwdbjCg11uefw==",
                "f4VySd+HrhfPV38JWuZJN6mVh1S18xLc32IRX1WQPXiAfw==",
                "f1D82AMbId+6Mgo1DL5Ed73sUEbi/si+5NgxJ9FcMRhmfw==",
                "fycXm3z57skVv15gy8+82KMz7ZHQgyajk0MsV6fTDThbfw==",
                "fyZbUC3asIa54f2B5qZAB6ZenvegKpmIP9x+qODa8CEEfw==",
                "f3AbGZK4Z3PzwIwmeWPqAkYmW/Ir/9MIdLy4UmJHauN1fw==",
                "f4hqajz4hpR+WUwPYv+yBXoKSNLRFDAwM/IXTXP5P8Arfw==",
                "f/tA7qLqLM0EPsB9PTyRmyY9vHJOceBJae5S9jAoczO2fw==",
                "f4VCEcZV+GggI77RYKp6O9Lm7cQo+I2sKNRLHIS8x1Tufw==",
                "f5TK1cau3Ek/T5zknQoHmGTc9qRrJ9LRN3NR9Bi56nmBfw==",
                "f6rgIJKBNz7YL/5qRrHBsM4LLX3faalUtOyncIER2zMMfw==",
                "fwx8U9uvMP0amZe0j3SnVKmnKc1Uug2wnsbFh7L/ep6Gfw==",
                "f+h8L8heCKhsmMbko+0TSBlrlRZKdqExF+FTYOPpCGmzfw==",
                "f928r3hEJRJ6MSePZ4DLHH8ExzyG2tn997qi6eVhOz8yfw==",
                "f3/I4BqoX8Co+Plf55dgPyXcITYCXiQWSJ+/cTrSt+WOfw==",
                "f/bUoLcJL884/1jBB7V9D3DodExWzqHT9KCt09MkBThnfw==",
                "fz3yTGa/NNKuGOAb+EGb65djAH8FpyUZNHj1JYNzeO6afw==",
                "f1AVx+aVC89KNbHOTSxRsiuB9oV+BCvotdpA1FkVQJETfw==",
                "f3aDJZQlMS396P4lCwceJgQ8AzQW6Q8UaYPLIgKW9VjTfw==",
                "f/btWbE4nUKTiFZHUyHCHlws9lfkQ+PacEQFsa9mntXZfw==",
                "f+4lx5SFeeKL1ATooThSif7TFwCV5C9oMbE5SJYVPJ4Gfw==",
                "fxBbPlPlnKCbhasIYAJOwzc4i0I2xSCBrIurIU4s9behfw==",
                "fxDJoJkz5ifR668SirFXsC8wbebRRNdkvqopwPIcWvglfw==",
                "f+zRljHxxFyTHTG2rY3vLX61x74/tpJeyknXu99NTJA/fw==",
                "f5rS2giO5HRIrxNVACqnBS+kb1XLFxaGi26GhszLZhTKfw==",
                "f61hB6PdLYmp6+hpRy1GeFHHokT8G3ChbuaPdFxHU2Jvfw==",
                "f5zRpL1FyH5HycUUo227g1RGQfCnOTiUPJyWggYqFMt7fw==",
                "f9EUFwK/GqLfyifpVbPZ9vgyd1aAdsrRg8HFbt0LgjkRfw==",
                "f1Vd2AfTSLFYQCXtAH0UrS6MZcS/D2HZdJCwFcphE/9+fw==",
                "f/guPXaEKFDjlG630iiuVQsIF8hYnTEtGCiyth4MjSyTfw==",
                "fzOtFPYGecmjpuPXe3k3GiOgS0R719TGOhbXuwGkoHktfw==",
                "f0G0clxVNpKp6aMxMh+e4IinB+Jk3g2pDdA4vZqGFVWmfw==",
                "fywyZ9TSv/+QvFu6vs+EfI0xDb3U9EpSEFWCTdf0UT4Nfw==",
                "fyh2DpyNqZsKfysxxP5Q1aJthhwbgjia39Rx5hPbUadIfw==",
                "f/A8ORIldDWg073jFQdqUGz7GRqnQr5L3AFjFt76uOBRfw==",
                "f6XMm/kiEYEm+ZjDdlF+JxUZa1F7C4DHD/d1YgZxGK0pfw==",
                "f2/aVTQ/g3h2EJZwJwMLSQ+Vc1eiTycQw7StPDaveBx/fw==",
                "f8cGpiN72MC2M2Kl8ONtZqeTY4HqsTvQ3GKvl2zBafcBfw==",
                "f1eec8HQqzkJIQanaxiAVb0VUc/n3CW2Wt8ZMwjIIsBlfw==",
                "fwD14tqhEfBcS7JhnLSn5bGM2Sk4cAeWXFRoFTo5e3K+fw==",
                "f3IE1MIsdyZRbnq+O1oSO5mlfnyBjarykZHAdDHxlvO7fw==",
                "f2VR5oePQgKcAlLHTqMAD/6QhiVbYPG8HopBmsFZQsllfw==",
                "f88iJUE0efi03SEEUqSSGXnmxV6xWe2YiWwZ5kVis1Vtfw==",
                "fxVzmEk0Ld8EzcHuFurkOOVs6mdY6GzwSRqCp3rDA99Cfw==",
                "fzFVK27+kT4yYq6G3ddBDwFPT8zYFRO4qzpeMn42WtlIfw==",
                "f4v+OCfP0jKE0HKE6sR7NCJsqNc5bybzoJSwwBfJjE2Ufw==",
                "f2wElpt5OCDc3q99nwUyJfoQNzfOIIVP+vS0AGRVvRFEfw==",
                "f1FaLPU3SXfJFYVpbVLdpRaFrqB+wgiX5irusOzkuRUhfw==",
                "fy8pkktfUkdtBSg0HS1zAWhQl9phjP84kRJSvp3I4NUJfw==",
                "f2VmFmso4EPWSC6HEMPamrqrm61r6eKdlhaXvpj1VTNKfw==",
                "f+W+K3nZ1Agg4KW0gm7bvobfGPNzWrgaK6pp5ivyMrH6fw==",
                "f3JXBDZZxPwulI6AlAj4VLbdVbLdq9RdTTAGUT64SV1wfw==",
                "f3FN/axqaKYG8k7dLHeoZ4LX9l0OVcxDdLYeDduU0aGMfw==",
                "f5aFZnYiiFomTDUwvzlLuPQ3bH6An/q5tOD+q2gIdacAfw==",
                "fyP4ft3iRDisGSmUdiyi/7Hkd+ZK3kfeNK6kdI6XrX0Ofw==",
                "f65GekXRtU0GShuDLtcF8YX7aKS7qMwv24kxzIKrzph9fw==",
                "f/MGC6dpSv0ft10c3S/B6Rs+FKo4PrPNOxZKzS44His5fw==",
                "f1e1dxKQuBlnNe1SE+LJlnf1qPpHhjUXPCcSc3Irp7rifw==",
                "fzYJ5hvcXmKc57/r1Kys7ctHCb8IBUDdBwJuyJr7/MfMfw==",
                "f2P6xcDHBHKhgc7IEa2ODrkVsMEfz7n4ntR8mtLj1sMUfw==",
                "fwB88HX1RNxuDx5IZ2CZtKmP6XGMDjIJElH1omBr4ZPdfw==",
                "f1vbTgrGVevQP0aXK4swmGB8zQl1bZaYUyt3d7amYQR/fw==",
                "f9fIHp+p626JFh5U/iubJ75bXK6lxBB9/99IlnHuI6fNfw==",
                "f2nejSPilcusx4GuFfXPN6eD5w8sRdinAv84vN6wKy8pfw==",
                "f8NOc2kTuwrzkCJg/G7GALoSw0FdZQOisLly0/ylcYccfw==",
                "f6iH0vOaqu9vObtz/F/JtuVj9L2wZENV1vdlX0VB3+Xpfw==",
                "f/yW/nQnDPqE1cSsb7O1JsY7EZjpKEMrR5ddWH+4i9MHfw==",
                "f9pqCKsflQDrjnctpapbpTTfjYXPwK6hDxs6wTwkiJWdfw==",
                "f1t28wGHh2v5Ik+pTJZHVXsi3L5PVRdnmJKDJT5+pd6Dfw==",
                "fzsdEdp/7Ma/PnX+0XtUSP3wxri3Upyyqid74iDUQlRmfw==",
                "f3qPWE1mtY5TQLlKQCYc6o65xQHrd2Meaf9Nl0EryikYfw==",
                "f3LPUgi/WzjQcxPnCHWDK4s+8DOHZsgDkUTsYsDuBz0hfw==",
                "fzuUYC0Lgaz6LF10WCoojiSlpVzPditZbkjPT4kI1icbfw==",
                "f1hnvCKqgjikdVJhX7QI21e3dVKY/zGZtkupVjPHHklyfw==",
                "fwaj5L2fL3+Bz60gvKTnbBpu+yvhS9d7Z4f74OV0Pz30fw==",
                "f7N9xTYfFHqEgRqw0Dr40w6nCnTlyaccDzsQcjaBrp0Ofw==",
                "f8MTdEpfAX1Ztzuz9udiC0UkimD/meDLSUFGE7GzBwINfw==",
                "f3vqF/gzS/OzqoZKyqM8UXJvLmkfsXzGtFDnWLfp6ANDfw==",
                "fyT+bhaH9GL4NV+KsUgflA0rZAaYWtOlas6+nMEwGBmdfw==",
                "f9i0d5r+0M7Dwt/S8TCSCV1MGyL+kEF3mpIL1poIoyDnfw==",
                "fyM93IOt7XhGheZrq6PAsXnZOrKkm7Y7nnRTA4mjjd3efw==",
                "f2HZTf260kr0EVk08eZAXotzyyCpHvG80dTV5fnOw1Iffw==",
                "f+XRsVFgUgNk1940/OhVqgp+i4rj9jLW4wbADu9hvgobfw==",
                "f+jIosImfIPxBE60H5i44rdOf7f84JW2LRIsbwS+ZkmHfw==",
                "fxSZrk1cuNfhwAHWay2mjYSyuKLPCujQXIvqhJHHiqJIfw==",
                "fxvyAqKVjX25ddQisqisdo3tGjdqwnRad1sBUz/LQPzKfw==",
                "f2T55wqoAm0XtbxxoRco+UiF3EFIxF6slRwo6Lg4TsXCfw==",
                "fxWjjqy+6yCPXj2eZB3JPKDGnQaz/ptt7U+VY8z5RT1Dfw==",
                "f9qFDH3vAxqz8Wy4n9B2Pkun12pvP2LEMtzaqYzL9Xvafw==",
                "fxvzdAWY/FJyHHudGdjxYOf3BE43CsbMpVzWGoHbVXthfw==",
                "f+BHnXRFyKR00I4b5fCqg40gtYq54Y9sHa+Jro2IU1YHfw==",
                "fw2Sc42nOcApc0+gmj9PG52CXiAoyAdN5X94zshTWB5Yfw==",
                "fx9kZJXm3JHYvaXBhnYdb//QnotwRh3HQ32hdzLAqymRfw==",
                "f9A/Gjes1CpaZYlWqxTtNJxa3Z6yjfuIrJbNoevlWMAMfw==",
                "fwOcEpdBJaGhbYfDTdbYhfODN7EyjXl10NAQ5PTBj3n4fw==",
                "f/Is9NXWdOutSl0BeG+WC29vo2pcl3SooR0nwmC36/9Zfw==",
                "f+A7oZi0C9IuwgQQEaXpgmu4ZihAu5lRg1tbY8qzX1Ikfw==",
                "f+QMzSRP8PVvQ3TdckdEwgFzb2wJtCYxWG8xbO1cYXxWfw==",
                "fxpjooPfPAMM/qnRs48bthMQPiL9PiPqEYeUdGL04PDyfw==",
                "f1pg5Ds/ZpP9wYwLJLkRu3FPvE8vtdPNSDMGN4I281ssfw==",
                "f8SAtJB8DJ9bo0PIv8Uhn7apBwPrC/NQJVibew6HBex2fw==",
                "f6iuSEKrNH6kEug6tJ02l+/vUQdew9xbnPvuWsIBZYbhfw==",
                "f/ykW3J6jHGfdx6lmX/r8eX2CDj0UwDKciuXwxQ6M7Z8fw==",
                "f9q9Motis7PXK3Le7R1RU7B2+bsXuNwvzCeyKuS/j5nTfw==",
                "f+M3/Bf4RReSrDCkme/IcNFqs7yheplTc1+4ADT6KYZHfw==",
                "fz36XcZItfzEpJdCMAj4RL8i87qpOBU9kYHUx2rCMp6Lfw==",
                "f04+mo3ireIprihIKvAjSkoxbPgsvZkKA2g47s7o5Pp1fw==",
                "f72psPlJWhtGLL1Oa7l+v+c0VydN/nqA4wbYLhLWyTKdfw==",
                "fzOxjzNSJ8+dKu4v4CpbVY7qzABcrYbJ0M88HI0KVGf9fw==",
                "f/WrSMbhb1a5CcY2ZrO1RcSS3s3+ICJ23RYnvPFP0hjffw==",
                "fzGaLNf5PgsCHs6eLw6fTKz1jglUgiJ3JUvMFUgchP1nfw==",
                "f7GiXNmuqewnmQsvq+qho/6CUQkPaS9TeSswUY8epVthfw==",
                "f+aVKlex1kr/PYPN0jvEXJIPbD55Ab1sKh9cilmzoJ2Jfw==",
                "f1ACGiiiQ3y55QvHz3sMFruOwsvANWtNOckSMlmXcjg0fw==",
                "f3i6fpcaozsf3yyQ6re5NRtaSR8ufRXp3XCmF/ijv4jbfw==",
                "f4D4uIoUKSlYF/QoCRmZmXh+QeshIFM8uxV64VWY5Z6wfw==",
                "f4BtCSKASa7jPXfngUnJCRsTKduFaCBAdIM07CaJ7VQvfw==",
                "f3j+mrsIkgDg5BAk26mG+a4RV4/NQHRMk5dIQK2p7bx0fw==",
                "f2zzAQvYjykYujhc1RMabEqH/fZ7uFTpQSs3romSWR79fw==",
                "f9iWUsPAgQ5UwaCPjARYDwo1wx554WgA5iJgC+x0RqEOfw==",
                "fyO1GtkPzN6RI3msW6SIKlK00MrS+8mG2MUO2M0gaTo9fw==",
                "f5XvOiZmJ9rqjxEGb9J0nPomwfXLgoqmJPDZA1ezLFCBfw==",
                "f05fLsrKleSGoTEquaVxy+2guDt/A+tuQjau0n/fMuTSfw==",
                "f3Id4Hdpi/y3Urj0wboTTpt1OTANMlDrcql2452T2mNYfw==",
                "f9V16+ZHv2nz743gaRVbR8ApQVai8DsUYCAAc9Jtfi6Ffw==",
                "f3P3KzN/8xnxqI4arTAlEYla6nO5OYkbB8qOMimZEuh6fw==",
                "f9TNZWpBLaGqnJuGhyEFeEx7VrjgpBM2SiXxYFST5GFJfw==",
                "f++cwdDuqj66L+pL4L6hgIRR749mrzZKv50fmLYEdK7ffw==",
                "f8V91tOsEBdhNaSCZ4IxMhBJfqrOQuBTiUvLEPDbfbBdfw==",
                "f5E73Zi7AomlmTFO1Tp4o6pMUhEOgZBCCeyQfqsi9bwZfw==",
                "fyjld0KPC57DV4Itxj0zdMlU4dTF6MOQnIjJXuMtuzGffw==",
                "f5ldx5WprL3xsZ4X4OWfNQAktdx+NrAo1eSJMeBqq0sMfw==",
                "f7qOduoeD1o21dMLX3Y73gKDLiGn3L6x/iIJQyFZk5Dmfw==",
                "fxplifPvkADAN5rfbJ0xk8+/limluvyDDB5VPEbvsaxIfw==",
                "fzCpqyDI41t9h8/MRraDoi5cIh5t02B8KVskwV3QX/I7fw==",
                "f0G93uLnlOinETVdSSWe+7t7ttsGdDwS5rzj8aaPlHC2fw==",
                "f1WxVILXGlmt6fFzz8a7OEKh/GpdhEaaOKr5fHsZiyjyfw==",
                "fzJ98ZoCkps4jz3oZXksvTUnfSQF0L/oZjoQb3WwOiqlfw==",
                "f1QrngJg9Rcm4ORRQIgRjBQ5VZB2vt6voVBvC/2vPRNlfw==",
                "f3frGBhOyV/lPrBSBcKbVGlbuxv2Wrb6PFO3YYHPKgWbfw==",
                "f9d2v8V5W+mLOj8Gwlzq6JOosNRtP92Vx3plezHlLpyBfw==",
                "f/hGL4Tph5c8MX58uO/VACCqfgUSfZ6MmUi7g7R/CwbZfw==",
                "fyIwHate7WRBgelu6CZzJUmPw/rOKUd2qLSh3ye+137Rfw==",
                "f+ldTQOcd9rieLx+yt0Zue12O0cF9+cFjYQGPRqVK6CLfw==",
                "f2JVda96ZaoChY7CoiawiQmJNV8xsA8sFjbHDXhRdSFbfw==",
                "f+b4tFn4+mD5c6IlSYlKXl5xBpweC5vkWweBKGrO1pERfw==",
                "f1Q/byLsRPHxPXjd5P7SiPg4Oft7xmutZGdHesJjoZFAfw==",
                "fxVS3uzM9uHnwGD3QnnwBDVP3Oi8hviNfARsWlkDAuMBfw==",
                "fzuUtJhKG1Xa1bCozHXeWpgnsW9VJrmXvJNOmaerFwd1fw==",
                "f/6Zj5fj7lIPjJPveKQP9Mzs0oUGbkN856NqxxlyDLkNfw==",
                "f0225TF3QogOyaDpXIo8u09mLzToU4ZRvq/6aGlwHLQhfw==",
                "f0Anjl2NiQFMr7orveQh9eQIVD6eDHsJbctVMyRk+cv4fw==",
                "f+jw3Ai428tBwGcQJyWq5RqxL+EorAzCo5k5MLkk1sL2fw==",
                "f+eMnE42Q4WWI5i8kRQAeJhVuZhn9frhBB2kqKpY46pYfw==",
                "f/i726n6jLJedy87LKUh/0r+zW4MUwhduE3OItuiid6mfw==",
                "f3f5gMcAA25MI6hABBQCTiXcs0yS6L/zNV7sfV159De6fw==",
                "fw2RVpuS48xwUtHLEkbyWMv1CM0vB3Yw3aEydznyHQ/wfw==",
                "f5MT5JAMOm+l4V/SS2/WrOz7aoy2n98yuyVDxhSzKNpofw==",
                "f7/kHmVpUNCQZzQx4jZKWUVhFpj9dFqSsY0JfAclzivVfw==",
                "f/enEj926aU6spcY12eLnRgPLoxg1CO1OoOYGV4cY3u5fw==",
                "f2hmNmcCKM01D+LY9qpwgZSUYLZkj2BdtctfSVATVRZqfw==",
                "f7lFiksmjhaDFoG7Dw444KjixJUzlkjNznVtHEiuMOudfw==",
                "f+XpJ3GC4qE15CcvqenSyaorsd25ettV65qX33TIqO5tfw==",
                "f8/h9wA2TwQ1WX1FAmp+lQqg2YQwTrmzOMdNt7QO1J0pfw==",
                "f7tiqzBh56B0L6GOfFfgldHlT2bbDU9z997u4QFxGo3jfw==",
                "fzk01QHTfg3I7OiqL1wPS26p3SJCh5kn7sMxLW2EmU1Hfw==",
                "f9ThL2QQ8NxRA/rs/VxhzZfNeZTnSScz5ONM8VjW4P1Nfw==",
                "f4u3ZiyTUpahsDf/8alV1kiAWeLKc2LsE3//s53xLYk7fw==",
                "f+LT+it49de/rwJ0cwRKBDS0kYy14FGi77ETG8IctCTefw==",
                "f8HMdRm+MqCkDPvxOEWikmA5t2mJU9poYxe81mecgc/nfw==",
                "f8m58LHQkjI4EzFvgqLsgi2vV88aTxnC4JFlwfYSpZnBfw==",
                "f1EtP1mVOf3M/Kr3mINb8raeFi9+EZ8CLVLA5XjbT0Lkfw==",
                "f9n+KCKr1YeZo421ziC+IRmpQYrBIS9npUVTtfXYkPmhfw==",
                "f4HnDSNbFSMxvVWnlTsu2xxvzwqwW9FAk41QB175keLVfw==",
                "f+8GFZ3eD8gaOCpQwYnix+aKJ1mAHsE/yg8yJahAJ1tjfw==",
                "f0RN3NoG1QFf1xgtgxYvwwFjYahjkRKftWbmEkxXA6lJfw==",
                "fwjNk6L5haq1kUvIl/9qSd+1m66+52Nb8d47H2Y9/WX/fw==",
                "f3w6gSLHIoGbCuBoNbUkGeUo784E/VFBlFLuAtGHQvIVfw==",
                "fwPNQBidA3NRLKGUkFuH6ppb4+lqE24xqxbNJ5w7cNRifw==",
                "fzKpwBpLIiKQ0e62QF+BcLTrZS3B+oVeneoc9I94rZ/sfw==",
                "f8UFQS45RdRGW8TqeoiXrCZuUjgmGYpIk3c5zoZ2wwARfw==",
                "fwyl+NqGbzGiS6WQDdYYHPuUxi9TghCMWGNZqjxn+DAYfw==",
                "f+JIDA1Crgj8tNtDoEAmRVbSuv7bmRCXgxrjNGW0fE0Tfw==",
                "fz2GcfndnIFDaxCaElyXZJ1pEaE1g3PcGah4UoT0wxUPfw==",
                "f9127y/BKZv05d3zkniLxKQB32i9NQ6h1fcGqpmuV2HKfw==",
                "fzVkjs/fCla+oKm/EWy+EebyRbmQwKjmW1TD3pckBmGpfw==",
                "fzr3jJ2clL8gZQfoLYzzj79BTeKtdUAIg2X2vHXhoNwHfw==",
                "f6q6216/DOJOqJ4s8htjzHWU8Goq59rbtRgPM50NWyGEfw==",
                "f1TbXB/oxxi/xYmPIB4uy74RoJyCsfPPOwExU7pNimE7fw==",
                "fyNllRF+iYiaIUdwdGwLmUiJEqtUdzE+Yp7mB/pf7qdifw==",
                "f+ShY/7zTSVJZZJd+rfYgUOmqHR9yAeql4nA25yFGJpVfw==",
                "f7sTIIivByAdZ5b5MhL7ob6o2y5EnI0Pv8vuv59QiZF6fw==",
                "f5xa3rOmTYCgGV2sVSu8eAHB0veYU+nGtvafQn3gPKAZfw==",
                "f36ToaKIyt4PLZd7Y8EUonxBbWsO9+qneL8xdOtmydYLfw==",
                "f+3+OhDxWOzePmsE8xjN+BFI4UGM5TFNEZ7umH2TImVZfw==",
                "f6eCEioK/bRebQsDeNf/10RQBADVs6jRGZYHQFChWvdAfw==",
                "f7hOWhjWCKb672V3gUaqxPHG9mBpW4jFmq1VBIvlR11Ofw==",
                "f5n7qIhBIXpultdCwdo1ayoLgtTt4BtdqtyBYWh74W0pfw==",
                "fxI4tU4SuiI1mlLzKimZOJ/TsMU+iZq78hOgVfP7ke8Lfw==",
                "f6HhOmpqBqe6kCxuHbvgVKg7BxJGIakx7sPE5yo7hZiJfw==",
                "f+yn9xthPRIPTfM/RyxWs5hTEfCunEV1kEBPmdGcm+YPfw==",
                "f+e59mdcZyoKEHUtau7Q2nTkrYrUDC3J/irhYoyxn/KTfw==",
                "f0zQoGGBxjHyNaBVlKrQKcMACDYjL4iMjF2Bjnj5PNKSfw==",
                "fxwUPcPHO6AusjJKIMwK/JiW8NH4KANLCkrz6oUPJgy4fw==",
                "f5Gnc804GdjYb11XfG9NDJDpW0EVyhF28fnO30yEAEjvfw==",
                "fxzVuYpeULNTNxxE3C5RBt9KaxPEjFMZ9DEsyVjrMMFhfw==",
                "fxbNVNd76ylQsUILzIpEndpBG9K+L6W5LZX9CEp0Rh08fw==",
                "fxlrcy0E9Vx9ap43UNRu9Xn4Im7AQa9DeDtOGXtFurdafw==",
                "fywvjJNZSZROQAYytmqeTXzxHAKpUJmugKleLwuUOvH2fw==",
                "fxiQoOr8Flnr0aC2Cjuk3+itafCNcbu8T23Mja2ZMJ7Xfw==",
                "f3Jy+8O5XIu5OiHbXTwM50fkgOpdSkCARImm2nBVhLGGfw==",
                "f4OQGVxwAcf6MdbMesmWG2WjIiwu42Wf0VmVItyqEjTJfw==",
                "fyAKe5rh5rhoW7x34enzFrptszPK6pEyDSbE+/xSQqXgfw==",
                "f5enxSO2bbMbsKbCyf70G6NGvEFtHuodcKJAu+8FcrIlfw==",
                "f5HGzfb62WrJEdQWbxp9Jtw7QhEZCh2WBRE3/h2wU2YYfw==",
                "fye4kTHg6OsSSF8/1Ae7RBqTkVQSFwEWM3rTFAXYEoYufw==",
                "f73y4gRJ6IfzG3us5P6w68m7vfXO6iIH6oq1mJMV2459fw==",
                "f9M+RWNXcfcBDMsOb2CqP2xB3l/cUnJ2pvrxgSDMu7k+fw==",
                "f4GjD2XePEnqUpmaCLs/u0k+MetvNUIwNvTZk30AcOzGfw==",
                "f66pXaxUcjGxJcgo7REX22bhGDLwJDPJugm5EXQhfoMvfw==",
                "f31v1PbD5exCsfPucVyEUUlPVkHTfXMfZVEKo4qZCr8Vfw==",
                "f+583MxAi022PL98QdHOpWnV6j+0l+aG3Zz/6y8wmDhjfw==",
                "f/XrOo61qwO4JQtj6xAzROsElyrmKNTA6Eob+7lySt0ifw==",
                "f2Xm8LFJuS9WI4M2yowgSnf065qZ0I4uL4AiboaK48HQfw==",
                "f63cSLNDMPNFy56QTyVNLiQ1uH2e0Mets+mj8wblpPerfw==",
                "fxJ3R7HmPdo02/kCpQOo8eawG6dViD1C1PJ+ISP3O8Bjfw==",
                "f2uDNB+vFqFqfkK2ioAAu/mb7IJVjG180zvF6IBriXPtfw==",
                "f3p+yK77fnj+z0gyM07m4xXtAvEcFx11yRfi220mqiA0fw==",
                "f1CG0ezw3QdRwBDVq3ailBHqbYUeaPbEpbgdhpEB2XAPfw==",
                "f+JJZ3BJk6H3RVbe2xDrSwtQnp5nBvtZNnj+tB27ld3mfw==",
                "f0M8dsLtpqz/CvRP3RSfnWPzxyMybzCHvG5fpIHMxUGlfw==",
                "f4u4Bue/y2lwomY7693MkNXlhnMuTHO7YIaaeOh96Tm6fw==",
                "fxjbYmJZfi8PNIzIa+H3a2y+G7yD7gssNdgeywm8NjZffw==",
                "f7Mz0Feywm1AV32Nhi3sBslSeOrRFC27Ii12zCzoXr+Bfw==",
                "f85FCCgugY0yHnqhR7LDQHAqIHpw6/iUhVBCozdwyVpMfw==",
                "f+fo4w8ZFPC5+zXsc9197k42A7vpm9N1Y/+vtnFUFHIMfw==",
                "f90zoCYU/CKhjf26+u4qxkjjp3ShNdGD8cSmSMgDgosKfw==",
                "f2YmEqhiADgWAHLhmBFSxSnBp/yXF68JLxMHZrfE7ihjfw==",
                "f8WEXiIvc039HzRpL2biH3iOipK6cB1fQ3me3fEF+WnQfw==",
                "f8jkWVtq7CEw5rztll1H/wg/+PaHXGJKkU29+WdofXHsfw==",
                "f9DibDvoRAasIv/s7CgdChdPxjCsqfxbLOvNMkeJ5tV9fw==",
                "f5oCGL4PTQ6HibLEXhBj+9iv+LhTL3xi8c9T4ylT/SXKfw==",
                "fz/PAq2ctuBKgP/CBkxqapNQzEDKOIxMrKLciWYbkvygfw==",
                "f3xbjqR8dyICh14EeIASrDvrYPLKo8y5xG3sOt1UOcMefw==",
                "fy7mUH6MWLCgzULQihb3htm4/ts4RmIkTowRjc4slT7efw==",
                "f3U8YN04XZKHjF5drb5CLbqxIEakEwS1kD8n05rkQ3cjfw==",
                "f15BkvFIksn75HXOulltT+jsv7WI1EfnM4Ge1PgtvC9pfw==",
                "f83Y1SoO/gYsa4ARFkOP4HwfYDU1F7KRTT9kpUZ/rWhAfw==",
                "f2Slpv7egEbYc5lMVnsVKahVAIvZ0Q3PzKsULa7xCbc6fw==",
                "fx0DB0y6TLI0mhBnaMIGsAQhFNGZ5L6/nP4zYQjgMo4Pfw==",
                "f9IAPmGjRJJCTUcXR16iJ4/VFrzqVQatOFINI6qhK3Wefw==",
                "f2m80NRgocdtWSFbGV4BX2y3RCrnfoTGRZr96lk6wBggfw==",
                "fxeMr7BoQ4rbXsOFUuoaq0G5R8vjpkOdCFnxbcXwT2TXfw==",
                "f4xFRyRs0LYOM9sQBOYsKSyHcBdwQKSMrLm0noC7mvZMfw==",
                "f7R2Sd8kuC+7Xrvv7yt6JY7YRQc990Jkzk4/rTM0WF/ufw==",
                "f+Hz8Em2/cBhbiQYeTxYCvbae4p33of8nAxzTBkNdccAfw==",
                "f2+uEy9J9UqFw0FQac2v7zSEPwu2yx1xLPrtrkbEZe3Kfw==",
                "f3OA4vqAa6WXCfggtVJ+fx9P9Sni4dHRn7I5lHmsJT8Afw==",
                "f5GClVHFTrHCdPpgpFfJZg2m6EObaZ5lnJAvUrclzhpZfw==",
                "fwQgZ4OSDGCYjNOEvQuiIS1Y2AxTVxIDaryR2ekYsqpXfw==",
                "f80fxciaWQVIuqgh2k+nx1V0T2tCNkhHkeH89NN8OpT/fw==",
                "fz24tMN0CvdEQ4Ktx0OeJjWdGO3Lh/oTdJJdSdBQ3gRsfw==",
                "f/KSZx1AkGVcjguS9WcoRYxD0K5BfqXUN6MyLo8G5Sydfw==",
                "f/2vtDXztBShpvLOXHwE9HMp0B1qLShJxQiKCI/VBDpQfw==",
                "f4Yp4yk19sRpauK7gw3KkEDTg0G9W9o5LK8X48KAPXWUfw==",
                "f5PcrqyyDoOTeMoKUBXtZlCaV44QoHpQGiry8s1jXOHifw==",
                "f8HbkeANVJouX/tQUIsTycMgWdKzr9EOLxa0p9l8CXMGfw==",
                "fxHz9QLuA8c+AlJtv3ARH/3PVr+3R5YB1leLBjrAIsm/fw==",
                "fx51YiMaJ6sjIXrvdDhLpoRT38KyOdqqtzYVyA83mUdifw==",
                "f7doPiyoW3JoloVRF2lrMrfYSUvJSLog4qnGwjXxJcbUfw==",
                "f6s3r+HQBF9L/YjyDr5v80/2dn7bZgekw4LH4PoeQIRgfw==",
                "f0tZI0V/d5LQjku7bFIdJHwQpjhDP950KfbGoXLsEFKOfw==",
                "fygiCDMLmmD8pqy3H94hqA6EjBpZXe1ozjaUxO15ACK5fw==",
                "f7IQY7hRMAJ6+NdGRWAw0ZvB+4ChpwJ7+kT+JOVxpdK6fw==",
                "f+4lk1Bt3c/DhKuRTWcfIeRbWbn0m69IRgngpCV8DQuwfw==",
                "f2b4HGMPrKrikDdQJ4/l10pFpo0b3l9vQW0BU4AqMDYSfw==",
                "f5IYUeVZJU1bIsbX4YgvpRBh13e+fWSNv9RJIJBurWlxfw==",
                "f2MmL3S9AnY56J2OICnuBJF5CSpydmjX8NJeE5sks2Iyfw==",
                "f5gpynrncVQay6ExvmAGGpstMFxy7px2/Iwl3ImgiOTXfw==",
                "f0lCihr6s5hmukrqpJUiFzv2mqTz2FvI6AwyEnuImXthfw==",
                "fxK2TxbySZmO2DhtHVmCcpdFeDYG0U/umm7u9btJ09P6fw==",
                "f3j0AQ2u3i+nywiAI8qee5DeJlJ1ZwcMjgGQL/2YSIDwfw==",
                "f6iu8d49Ap0wgLDyPWmChdEVVfl1gLSutykk8OwL2aunfw==",
                "f5FOWcYYgPyfz26IJP3ppzFlW4dkSG+xAFm84GzD6h4Zfw==",
                "fyUF7LN98HV6Zz1n3Jpvtla0z6Inp+QDB7RrmO4mjsxvfw==",
                "fxn1BEAiwUZvOvhQXhENFw6xWetiRbjeb2sHM2EwPFlcfw==",
                "fz2I/oB9D1uhlK8Xp9U5RwGI5Ymq58j5MK5JurmRum+4fw==",
                "f+STbDx9xvKD40czRAQk+w7VxlKumU1o3cWfSz/lqekJfw==",
                "f3oZq+GqizHFgpySqHWNXWrFzIZK169aXJS+Fg7BCRxyfw==",
                "f0CX9FbAkks3BHB4S3Vci1+cGiLV8ZAXoPtSs8wLLm+wfw==",
                "fw3zjsgXSantYX03+YiUH57U7Ubmbv1NpnFB77p8GTL3fw==",
                "f1sk1bQjVtYPh6DT+st7PXvkVjSeFGV2Uq29WlccPvpzfw==",
                "f/MtSLx0FMDzzYrhJe5G09UxklI7F8ufOZuUgrWlKLBUfw==",
                "f0CNYG9bItNzAg0fwWAvbqaVnus7etmGeMya3gJEfaE+fw==",
                "f0YAeNSoXvHGhKplQgDV5tNExhmPbINeQ7noARzArhuXfw==",
                "f02xyAVBdZjVCPEw7DV3AWbvbLOk1ogf+HpKpGLGVXYGfw==",
                "f7OV96814Vng/V3Ywn5DBhyPy8Ul1Q9dEUjocN5ECUx/fw==",
                "fyZMX9MHi2FnjXxOIz0RoIkrJNqb0GtJvWbqTXpIm/A8fw==",
                "fy5s+xCCcQbDODNtSrBk2182iWKNXiW8jmvlSJaC5sCsfw==",
                "fzVGdWDQCky3m3DktkaNL1hy+1EtumBQ1nfqnJl38Wwxfw==",
                "fxIq7yzzOvoEU79d1gY2C9ZAJT+RGypVwKATOKUa7ck8fw==",
                "f+93nJFY0GGXdMvRVv3yqq3tSOVBi3IbexfC4NszVK0efw==",
                "fzxEBFFN09WqmaKFmeiyST3SiAyCfT3hRfGLWki6beiFfw==",
                "fyWEapFCx9rTGMIVRIHAXOe5KHgPiH7NUbSY3HM34N1Gfw==",
                "fxpTnAvYGHpESjny7pFI1Y5iIiuVf0GpislgMCjidffyfw==",
                "f03Obhw8S1YiLnP5ICYdui7RGQShJCuNTKk1mpZHSrkWfw==",
                "f3Qq4hIqjyxvMqzQ3cJfVN+CD4M97qXTpSO5P3ZkeKsXfw==",
                "f/lQ+SuuEXrCBctB0WYGprlQMUZSf8Rt4Uuga2cHkcLrfw==",
                "f7C7Sn86oOqKG8/TXmmtO/aHDa6orjLHKeLRSvSf0lTIfw==",
                "f43oolhlaURQpl54JLf9AjkIA4fjf7XYaVDRQPUq+TuGfw==",
                "fxQQmjjR+bjGIwa32VTOMM3uFbWCLgUPXJenCoBVBzzqfw==",
                "fxHkqRAbjqu9PymyZJbE74gvgeVpj1g71WodiBH2L7GPfw==",
                "f1O9wNttBVgUhEqKbZLNE1TnPSpRvsWGIzfBAF0GxR2mfw==",
                "f/rB+DFRC1OfvLIBx2KjPJ7gXoyX26bzcLMXWdr4q2rtfw==",
                "fyvY9WnRyUWK+iGlRVRG9Yezknes8cxxkYiuHt0WGZ1nfw==",
                "f1J76fDRrk34hKhNABSqcR1BHbD9jgOKXxf+hWx+Sozcfw==",
                "f+yd0td9oPL/lrBHTrc4dw/MSokBoxHp6/iYbwPwk/b/fw==",
                "f8uVyaPl9Z2rC1vjUwEP593U/wnC+Kqd2YHHczI3GoXffw==",
                "f2/JugMz5Ny0rqopDcNcrciGEO6C/5knwKsT0UIYk/9Hfw==",
                "fyJnQzPdyCMpmCqAHIoZl5rgpmzPKFZdsFM4tKAMVnfGfw==",
                "f1ce5gytUf4Xybxmj1oRG1VQpqbIMwWhEkgL808IcJZ1fw==",
                "fwuP8q6X2W+Nxkiz2JmoA7BNKWdG6nuDCO2cllqoc6Vufw==",
                "f3J5KcR76ITXnFRdLnI5dPhlRJm/yfSo6zO+6OUt1+Lbfw==",
                "fylx1ynsOPCTbVDl3FafjkbT1oL2z49UzuvLipCPT1vVfw==",
                "f+tJUeZ1Rbq+UhXwH0D4MnjQJDLm7q8j++wuy4VavDXofw==",
                "f1HSHhg9twaiu8qBD91N5JmnFPuPoQdLfex1wsnSK/m5fw==",
                "fwC4vW6jCSlFDnj0AGOYATfS7GNaMvQfWsWRFGfDAVwHfw==",
                "f3nW4PNoQTwyU/ywEKIVZAhejCe+ulR9tNp20Ln7PlZjfw==",
                "fzfngX9P1+LGKieOZSYQbrTPCkHLEeCnJ5f1nrZQWTeSfw==",
                "fwxU3EZgJ9O7h3qjLeXidbrHrP5PzM7g8HnqpoKvlsNpfw==",
                "f0fcYzoLSY+sdplN54GYIjhbk8F2vItRzySQGO9y38iefw==",
                "f2moPzom8bpNHnBzRucBG0EIM94U9XbOS7suHsJLK+DPfw==",
                "f/20fVRvRWsVmQGub+7GGXgV3+zcYtnVzqfz/s3hjDY7fw==",
                "f9aadi3aXPGhz0IzqT2t95TP9tgR5d2eWn0eCtxo88PDfw==",
                "f+7I0z4touoUnWI4Jkb+uSUc24ft946qAKCEBvn1r0yvfw==",
                "fxni3hihoGKJKnDLvA6kqF48YYFd4n5wyYQu1Jppa4yVfw==",
                "f28GXXfRr0ltxlZBqZ8GCuKIeydX2bSecre537Z7IJ5Mfw==",
                "f8R/Y7Vvyc3BwkdcPte4nUzfDaJ5pkinOTzCcwQqXEicfw==",
                "f2sIvWo/HqXakeAXdu083hSO3z/UkicKVLe7dRFSKIhHfw==",
                "f2PL96o9VYVIZEuM9wX5gvmBx8wkdG82VndsWjmwENV+fw==",
                "f5DjNyIMM33YGKdSJ6HhRv66HrWu+DrA28Ubh2rRRYzTfw==",
                "f/9xo6aEdwP1CYAjvsckd3oyrw1kWwWkqkJBq/sVgO9cfw==",
                "fxKz1s+Dch4CWiETJX1j0wu2dTZZFe/vnrFd9HJCeiJMfw==",
                "f0Q8NLTheo9GoDhvjdsXZ2CJJSPnAux2mdAfvtD/4+yafw==",
                "f70GaXZvk8SA0RhntNVMbANh0qiLiz19/JOaeg+728rWfw==",
                "f7HqvhYIMg+oH1Fw+gBgqvoAS43PXs29qtoodABTepBzfw==",
                "f8B8hnLF5QvcwZyTTFAifSactO4iY5lMK1eRqgaA/qjefw==",
                "f7MvrJgF7FIuCBHviAKd6ke+QyOcuzwFn52BhiH+yNRZfw==",
                "fzzJxs3w3TOq2K7In2mg0UfziqnCOPjbCl8ye6+b5geNfw==",
                "f9nTlpszG/yLwg/w4+loN0kRXbtsduDGaBQfj8i8CvZNfw==",
                "fw7sAm9osGHOFr10wAxhIZHR36xFnGsT1cg1p0OBETcvfw==",
                "f4gjJG1TqzDgvXhFLvA43q8/XjBtqne2VgMdJ+p9iLbJfw==",
                "f7UbtBZvA6NapV6pI6lDFnehBwmIWTxnznwj/7uytc7kfw==",
                "f2Ts+IfHWOF7JkQzf6cnw8L1QJi8xL2u0P/RAcZtow9Qfw==",
                "fy4lW4FWPpQj6yPM9XeLycWJQJHOOofHZ5Ao7Bfv1Lurfw==",
                "fy2Swan3VuSRjjcTruCjJk9+B6F+05frP2+aX9jeXyh4fw==",
                "f6A0gwcHOI9mrK3g8hLNOJcH28ai42eE3m1cN/S2wKWOfw==",
                "f1rQeUehSQt01VLGHGcujfgYn7Q5heyh+EcYA7cP/ItKfw==",
                "f6gXHC7dZnvg5ms6P0i5M2GlKxu8v5RQWGJvZHWgA/lDfw==",
                "f4ZWrNuWIYZHyD5iWvtPJ5aHazc8Z8/0AOPKDgF+zMVRfw==",
                "f3++RlXcm5t0t4kvBGyvFI+8+SYGEYQkXz0cMWqFlnQLfw==",
                "f3SIE4oUJcvm7j6G18lFDY1bCfbos4n9P15t1pmohyO9fw==",
                "f8WoKtX5wAtNVg3C009IHWYqUe54Ii1rk+WAqcn6p8/afw==",
                "f3vOSiMN2kjl5BrE2DSJG5QqU/GR8xr6ofj/YF4fwWaOfw==",
                "f2lkPouWBYK6sz1fks+Qj+pAEryxvT2u7roMxJgDwJ5Lfw==",
                "f1v2MaGgo1463h+8F/7K0OJQZleI5a8uSeyiWaJ+parKfw==",
                "f8ZgE7uV0sPPl2Qv2sc2VulaZ/GACnGYwp6mEXQzf9cDfw==",
                "f+Ax8d2cYknRo6qpK0WbMGWM0+HSpBJFNNr4/I08vRrFfw==",
                "fwTyjC+KzziXEk+e2SnY32+gDyhNb9r5eYYDf+T0fVQifw==",
                "f6mNTWexgMxPevSYu5nppfWCuy0ValEnO0aJJuoJTBRbfw==",
                "f9lGsL1RgkbaXesdSnziXmme/p7WEqHjvP2Y/CUXPbmxfw==",
                "f7BvYx7auzHnJ7TkpSr/Go0+EwMZJF20KynrVc50Oxykfw==",
                "f7dvPzkCbLHmDKmBlfgP1ZEvaXsI75MPGOk5jvnAuZiKfw==",
                "f/ilM7sXfj20GxN+zZR3Tg5PAk8MFsnR458cOwbNfJn3fw==",
                "f8/EA+E9UiLQSip0SNCgBac3SH2WZE1CL2cYWBwRlIkdfw==",
                "f6P5chNg2gxw0KvcYct4kAeyyYdZ5WBdobFj9nvzNmjpfw==",
                "f0qnNVMYTapcFeAYVEHlkzSCZuh7ZlTj1dWMgfHJbfAxfw==",
                "f1vpA0IVZVpsuT47Jy2JBiRMAP0/bRUB52rwq6g1cHkbfw==",
                "f1KyM/B0Gsrxk/pJ/MpZSZLPhAwQncigNZqgmffxuhCWfw==",
                "f426Mu1xTRoR9kqs+ND0W5RpvKsYT31BaxK75f3UnjeKfw==",
                "fz1HSUi4ItOMXHdByOvMM/bMAwZHEyamQlP9nJRm8qyIfw==",
                "fzXsIE8KFdPCMzWBK72V4YCxReZufCSV7aK53wF/lFPPfw==",
                "f8k9OyAM7xxEP8xX5AWd2t2ouQFUAEJJZDWHZCkptRr4fw==",
                "f5JBL2iYVxMmV3xUeN7iLfbVKsL9u/0nrTyoUVdXdtPDfw==",
                "fzhiR8k1TYOaHmenZaZIpTcoxG3kvGbHrTFMA262lcYbfw==",
                "f0XLUDV/F3+W3H5b4GX7JAcGZm++ktyXqxuBfrjyCp2Afw==",
                "f7Ig88V6sNwtHASlQGaBSAx09cS2WigNtoseg3YHkoUXfw==",
                "f0rOHml4GqigvzUG9I7G1VMC7Rbw3j8l01xcZqwJ1u2efw==",
                "f6wxuYzHanhynSqX/AXXfbxYX0zLNWCcgyd5nKMhitVcfw==",
                "f3UbTPHHkxmPXVbTBtIG/lNT5fXqXPkJjnBB6YOkE+0ufw==",
                "fxNpP+AunjgLMfPDiRBQEYPjmRcu8XJVuHz1djEFsq25fw==",
                "f3TQlpbDvEdUoQGpDrdMOem5kziwRJdLifl3WiWFgi79fw==",
                "f19SRvnNUs1+MI/f8PVVCjFik1vCJKUGgQMsYjm5Stoafw==",
                "fxJBeYjNNfQoZ4jxVvdAdIvxj4zGr8wVIymt3NII/YFbfw==",
                "f9n1U1Swgq3zl10J7iluUJnsdP3VvvZn3ifOX3eARwj9fw==",
                "f7/yoODyJb7/XwQmIprkD0qbdJBtbSrZSGf6Bs+O2urUfw==",
                "f2oNkwXuJ6xDUwQPmjQ2nWstJqv+g8C2HpoR8/0oH3dgfw==",
                "f3BYIgF5jpeU+LfhW9fQCRsZzNzkIJX261aeHaCyJBDffw==",
                "f0sJxiogImLY2Y9w6wcU6G6/fruST0QonxevBlwdAHIQfw==",
                "f+2TUON1rVrRanEfraTOxrKsMXF39aJMxUaAs38PK3KDfw==",
                "fyhSzpCHzKhubkiH7w9C/smnUo5zL0ilbvXLF6o5jEH1fw==",
                "f8j79SqxY7SyFkK7egNJxOK/KSYZpowQfuepDWYRw4EKfw==",
                "f03iQ8Za/L2thD4481vLrWj/u4D0CGJ8M8UBYmqGSreKfw==",
                "f0MTKaZdb/oTmiAybrFFh3OUiqbtzgWHIjIq36B5h3Hhfw==",
                "f3IKBJnqXknP447/xpUS/zRlizutN5wH8jp9JDY3pJYpfw==",
                "f1OWB5s70N+TswuY6IAj+9SNWyC+1Qv8cVIgtDtWao8Wfw==",
                "f/0wnT0HluHS2yklS1HTFPPTB+K7tBI608siFmJd4QU5fw==",
                "f7lz4GVWnSSUE6ShShscguyUlTbkf3qmCO3haEc+vRumfw==",
                "f23Gyt6OLEbOfuEc7BzDjtQhztsdI7F4/qckiJ0JyVbufw==",
                "f1WpXkEYZqrt2e1YXegkIVmq0MYG0MhAnFcX0LFnilevfw==",
                "f1Q4q+GAnfM48c/aIq21/kgDZh9q1AR9IEousLz2jS7cfw==",
                "f1wzczPKyitdUuXGqoRcbjUR3Z/TcpXHu3nBpDSzwy2Ufw==",
                "fwDLJwW2sW8jvhxjIxsRDtzaGZG3qYQWYGkifxUlQMx2fw==",
                "fy/VBNwWIBN0xcftCoWOrPKLf8sbyLp9lFKJ3qzf2zazfw==",
                "f0AzKlV6z+x7IXXZeu3srVS3SXkaYHDQLNIrt3i3QKJAfw==",
                "f6iVGgn1NHx/LaC8EFGwRm5y8cN5e0JsR8FyKSk8HG3Dfw==",
                "f6ZlFHvqWBerv2+2eTlzu/dN1M0+wZEK0RMrXbUwBWyHfw==",
                "f2DnaEQvCkPS6GbakxGCfLRWetb1taUW7sCFZS7pEgU+fw==",
                "f/XE7TfrhJ+t9s1sTSnXsBStc4+SxwCG/W/ajCgtZ7RQfw==",
                "f93fX7hCHJLP3ZHwBGlj7r+/qZv5pEoglUmjjIb7z3ijfw==",
                "f3lIf9WWuo+cUJ12Tgv/MZzbGgnjZcBiLLdvUWq8ZQ0Wfw==",
                "f3+gE6zWNVN/2OO0sBIX2gtLxpfKsPG6XZ7mGQQdFGJVfw==",
                "fw/NcRSb345kP4e1k1TXAeaUrcFksRnTi08JsuxyoVkFfw==",
                "fyeGMHV4lfVLaFyWIbgmo5qSrRuSG+qheWOq5tjh7LuPfw==",
                "f6mqq1MG1jvMvWoHfBRZHCA4UgGD+N+cmpQAFokJSNxifw==",
                "f5VwDMKv3lDm7jyvtMRMhKoyIKjNYCDtRqly+79rSvpKfw==",
                "fzmMmsEnq6bWC0ZUUwalzIf9mk2I8qhSRMAQSqenq9KBfw==",
                "f4AZLEKk84pWAWWYJsRDH8r4c8yzWOhXhV4c8zJ2ReQCfw==",
                "f4YaRearyPw1NS/qn9hWCAF4pG0AeAY6hClVaCs2aPzefw==",
                "fyhgfdgjfJ9ytR9vCxFgVjuJRHYMOAMFCxL51DB70aebfw==",
                "f9WDC6HQX83UY5artyZvNhVabGRMTFZMcEG40vtTsFPSfw==",
                "f7UEwbBzD6bJRnaKMqpfEfa8YdD1xxGQkTnfUrFkr73qfw==",
                "f1tZi+jMHkw4ogeb97cZA31Q2mPsDjHifJwAUtI5I6d6fw==",
                "fyifsz91rwp+fI3nkgMlXuJrwSRPakhYJKTGycqbOcgZfw==",
                "f8S9cjGA25MYj3/w+6Ai3jUMazP+Xg9MayLrKaD+p9Lhfw==",
                "f/dS8Zacjj647bqr8zAl10Zwf0i8rMIJuc2RVNnfJzdhfw==",
                "f8xVLOtkV1Q8zm9ou1uNzYtlCHjwwUSgsFST6Ok8uL71fw==",
                "f25y4HzgZBSwfCWbs8c+tOgjxChT0JbS/MLI7jjPf0mzfw==",
                "fxKZ66fasTRo/DpWKuSCFxa35HMSKW8VgnSfktd9zQ0qfw==",
                "f3BLOi+pWlcoyWv1lQZhkVa42uhJKIB1u0VaiKmhs6OXfw==",
                "f4KBSI5evrrtUs2eJSfWm13MVroG6I0xsZZCwlSw6ewqfw==",
                "f5M3FP2ieij+qRLfEKbpEfQ8cSKFt6EW4OE6z+SuNStdfw==",
                "fw+mqESNPdUA/gPqA3Xcn4zmztNbb+urkEZDaxl5uQsOfw==",
                "f7HkQ8oaq5AR2GSHsqQT7jaZwwWYEOEUsnibVPXLhVXIfw==",
                "f0R903zrlhemQC94Z5idEY/cW9qmu1h9XvGcauytMdR4fw==",
                "f/WtbaWJFJGAGYUN3/yhq5FN5q+ZgamxQdhmKS7sM57Tfw==",
                "f/6CHSK3IjP9tiaoMTKpEN0PTdbXXurjyANKb12NXvxlfw==",
                "f0QTlXFovLiIJ1btjkStYrvrarBveErUI9YOxykjVHDOfw==",
                "f5ATmXcTh56fCten+4gmQsjZqXOcBcvssxw3cC1k8Jidfw==",
                "f/VEpxKyIOHf504udvJMvvG+8h6LpMEE/qgKNOYP5Gtpfw==",
                "f3Hs9vZit0RWeldks/iCxjUZNH/Gk666jQ+5cRoaJ+9yfw==",
                "f2LtD1leSCPReTHp+MCz9IMB71QfZrxaMa0vw6k5ZrJ4fw==",
                "f39UINGYNyFfkhy3atE7WyiVAgASPI6BreHP6vetMnYjfw==",
                "f9kKpWOsZjsJsBm3Z3H8xH0JxBiKSQVRwPMogMJOjp9efw==",
                "f4tl0mSlvo2A8I6CVFz2m9doE9ycr99GJ3hwe2RZT0Byfw==",
                "f78lOk7BbZk6ptdMJcUGGsY/gOkac34xYNzKu6sMTXUOfw==",
                "f315iKNRvXSfIWbp5nUsMQE8B3lD3351wHmv5sV89CWefw==",
                "f4lmS1RIby8Bi/d/zGv57PHMhjxikjkOUs3hZjPDIo8wfw==",
                "fy3tv9UHRh0VsJ0EWTNoDkM4yf7dHjckLYclctTFmXYkfw==",
                "f4EXeSUakHba2PnR6YNvnUXprbWjNyenQNWcmSg7mAYNfw==",
                "f0rSd+HwNIh6v1rx2XjeBkeUQD98huEyGa0pG+PSMwE3fw==",
                "f8MLoZgBkmwlCOj70iGBLYp2PvdaoDkZdDafLq+V+50Tfw==",
                "fydlhdmvhx3PMkYXpDb85CjxJdoDbE9Y8M7+co4+66a+fw==",
                "f+rPJhxa1tCRJJvYvR1A4PCQbB3t4YYlIr7lnc1r0/qwfw==",
                "fxkB83kN8Q+rHTfZ3hoSHyWQEIntis9jnVp7z0d7ssfafw==",
                "fyBKtJPbZ3xzXwgwAp7glZAPfzm2Y8n1ZVCOcsN/7xz6fw==",
                "f2i4wU1bM95bGNnr826g2gLj9zf0oMNquau0tqXdexUpfw==",
                "f+h6MuDgdVOQy3ah0peXHRXZ02WAsYK+MQL7EgGzbR3rfw==",
                "f46ygDSYOX3t5AjFWgFEJv3xjbkxHOg/f9UbPSih1UZJfw==",
                "fxd7QpHRvO0AAU+DNVKn7TmpMB9jg16il8y69bzZ//5Rfw==",
                "fyFLOLJBNp+msVCxeXDiLWUG8tFmh6iaFwmgUtPXFx82fw==",
                "f5XXN0RLl/Sfkcq3m1kGlUCHVGYBGqBAuYobM42rhTJTfw==",
                "f18mBhFpZQg2CAsKu5aCoWnAjylofVbne3Bbw4tFbh42fw==",
                "f4H7dCt+vLzXeUHfajW3W3X/MTZ84EA6KU7ELby1nFwifw==",
                "fxbQvmfEr47I5BSwQxd2NNf1QrVyp+L2ufANQSKQdchbfw==",
                "f/4fMQ804X5cPLl7WcW1dep5GnduHWaZOIrM7q7grz3Afw==",
                "f3nXOF2foNcKWnwDzV5Abooq6daXlevSocYq14PcZ5bXfw==",
                "fyZUUfUir3K5/YkT1pbDNCSP5NbmER6QK6hUdxpFbpqjfw==",
                "f//1GtDPbzWoMyeJMe22Yvu4vQ5JDgRiaJcEm6/PfFWafw==",
                "f4rp0wcziBa65fWZk14XWgrpHFosxe7OaQGWvoevv5+Sfw==",
                "fzeiQ7dcQwF2UBzzebIx/80z4RSndeQCOV9MJDAnOIx7fw==",
                "fwZR01qgAXtAwXB9YsAyrvFwe27jMcOCvEv+o/4NIEJFfw==",
                "f5IULunWVdUCHqLyN/HDhCtN9CGVhat1frZIyh3OLh2Ufw==",
                "f5J6UcHF7go5zLy5r3CZ8tKAbj9RSFGRcHvScBmJeI7ffw==",
                "fz51RbIumIj3juR7F1A4kb0+yRaIVfAuYslX/2rJzpzLfw==",
                "f27s/FFvvwsXrPh7OQtSTj63BQRUzB/fEtFrVibcSJICfw==",
                "f/PRL7FXJyVi4wLZ31T92c3rpInmF1T2HeSRoAMPwKyXfw==",
                "f98p6NCcgvxXJZXFKTxCij/MjVpPJL6KTdH9hpc1BdB7fw==",
                "fxUifpjcYWfWRBpPPJ0GZCWiGymDtOV7HhejpydSVaMbfw==",
                "fwlQKVHwYmDJkt1k5JlD99SHTZqXChUwsUq8N0ovk2yBfw==",
                "f1nM2jcS4irAtqMaSAkEJL/1gGafBMcpoISEDiX/qsv+fw==",
                "f1f7m0/T8oKISYNXzRmnIS1LsxC3M5iOJfGgBbBtpLtsfw==",
                "f3p3yJTcfKjaOY336xYYJ2Kt4YQfd2tA3bJsvEp3H8IXfw==",
                "f4ZefPjJVPM+ROwi8xfAE8lw5RYwEwsSLLJ/YPv1fNQEfw==",
                "f9jcDqryJl6zDOcXS6RpnzrSf33MEhRP8SD8Nf5A3W/hfw==",
                "fwUGLoWkTusJvdAWy+GyOWJu81jcGUDBHunD4/AKXCVIfw==",
                "f+UOAhF7aOEVAusHtzTIZQj/XD46Vn8ur9OsFEXnkn8jfw==",
                "fwt21/H9dJnk78eqB+HlQSA7f8hrSHINT98Sr8LEAbixfw==",
                "f5VmD6tJsIveL/+BZd5p+6SWfc6hByuppw4hqQNDRvH8fw==",
                "fx/l10Szfw68G8dB+/6FORgOJBTRxM4TX3oy4Xsc+Sfyfw==",
                "fy9gQNjYEL7q6BW+yR7CWsKRvFUM3XezvX1yDNTpjt5Dfw==",
                "fzGOXRPSvQff5cIp/phdhgrvyBMT/5pdpTe+N9q3ym17fw==",
                "f1XchBg5OUXR9ES/31Qvni/4kkzWb2v39wkhdlts59nofw==",
                "f2kJmVpATmVqheKYP1IhxxhJlF95aWeWotukSy6Mvj1Ffw==",
                "f8Yb/I+oELOSYnsBtA7j3BHwscZ8y0pDCmjXqdLab1tqfw==",
                "f7ovKLSfQAsesgG5piZA89X0vq59NZ+hB5mHvxiCNAa7fw==",
                "f1It7fAW9zSuX71w/i+OQTdCoqJt8FXUDOvmLDbRmYpmfw==",
                "f+KsLBCKUKBZSQQaGV4hAsqa10N3yIMe7DzbrkEP0jOBfw==",
                "f0prBIRMziwwTXyaovDOCJzvw2cFTx2xNwGkLbO9icaZfw==",
                "f1bTNGWkV1Q5fDuOgJPZ/hIsqxh7wR8YohiZX2akSb+Yfw==",
                "fxDZ514tsCY5uKqiiBBfK0qHxZXdHx3W2Y5U4fED6TPPfw==",
                "f3TU1QfNTktVZAJl4e2ytHhZO0gHr4RO6eVX1UCdXsmofw==",
                "fybimlGrvxbIi/3pe5odseWriJdSDWahCzw/2+ngDwUffw==",
                "f/LFHrMbLRkhYuKc4dvtJ+phMeYfK7uxnGIzLV3cLZKbfw==",
                "fywvTHIKKL94xFatOaQe3sU7+gQE2ZwQ9u+zCUxiCv0Afw==",
                "f7b2g+jlUlnzvcfdvzTGk2ax+rdzMDYc1u07XduOqXEafw==",
                "f8kV9N2oifrmXtzdqgmjQs/PNAoYu4Ttjp/J5WZ92T55fw==",
                "f2RFeKcxUT0ZZVo6bp0TFk1BmjqKcnenPgxjWXA8Usx8fw==",
                "fwKcD6tDvhJCIBII3K5oBwgf9SIMlvbX/TJb3lLxxT5afw==",
                "f+zLXiMlCW+8NSR6wnR8RqhfStOxPfw0SyfMiwyDaT0Ofw==",
                "f4gnETMnkIQ5PzWOUgY8cZQ8eeGOpjeoTcdCLKY9krKFfw==",
                "f5DD8vSk6ynM6yLEvtxaYs22kjAyQTLnezlJpW0lY/Vhfw==",
                "f6MiWF4PzkH5gLTfhDn3PSOeXkm91qdjvAfTCQpTtOY5fw==",
                "f88epZf18GHdBWOSGXLSjEzmcpNYi75gBMBu5x0l4IKFfw==",
                "f7NpTsXNeFYZROdSuCZxtjpRuyeSuHJhUthjWAidyVYDfw==",
                "f19bD3dJSBCdrOkmkSvFQpxpkXOBKhnlSYQVIqUBcst6fw==",
                "f6JAFi/JuHyyQ2rpbEi0sXbuk6OgXDUs5QLoN3jbRUDcfw==",
                "f1501ieBVWL4HDj6tJdzQcJy3lwHD/mVPowEn6tRkkYefw==",
                "f7u4lsWLjp4O7kBcmsh6BpDFLJKKRriC0V/P7YKXgSR1fw==",
                "f68xGDw/6+RE9S32FkOZWRWIl4mJEu3e+gAZWUcUDMYvfw==",
                "fxF/hOH75Eoi8dhQqhD+sSVqIdkZBS+SqYhX/RLQ4g3tfw==",
                "f2ReHdIDayi5yb7RWFNTSboKFez4VH/d0NJu4LOU+bTzfw==",
                "fxfju1VqH7R65ocLOOE7JRGlQ+crTBQxXSc7bCPCKm9ofw==",
                "f7EJqHhni/JlUUtM9fHnJHbGVKVNAXiN8GRV86LqHmtBfw==",
                "f2wDkPABYJsp64vasXOahzN/TnspT/fAwLfAknzeHv1Zfw==",
                "f56VgFbfSYqtqABe3GYjxWWdJm0q5JxdxTedelbla3qafw==",
                "fztEpbQNM/bO/ZJmG6LAIyev8f6nHFvp49sZgBeWMfn6fw==",
                "f/hxPMLnHJakmbduAr0lnlAjb+0uhas2nFIgeHT3um06fw==",
                "f1du9vl1N93zzyX+XQHlELT43fmZTkk8Sf0Jbf3dx9ayfw==",
                "f2xqFAFvl6HDjj6lmIRD09EnRIybJBclSgRppC9hqFuRfw==",
                "f4PUPFaPuTcaIhz4lQvRi+koeNuwI9+EnD/frv0MiSGyfw==",
                "fy1sqJ5KBfLT7UZb0tM5qh97KW4KMpUnuWXfdVRAyEbNfw==",
                "f9JhPaWogSiCcetkr4pyzzQrRLtoxeBUiZ2Wym1Ql8Vvfw==",
                "f7glzCOUXHlt/oL3HhDSh1HoDIQ+VDv8JiElhZL0/6+Sfw==",
                "f3tGMahOQWuit7g4Puyqpin12B5lbh91PRLg6ja3RClifw==",
                "fxUCy3VsMSKsabt7jNJBoYo0tpwkbtT+GohS/KfoKWCofw==",
                "fwktLB2cgR0H8AvZiAX0HnyxRCKCSzaNmTqcJHvPpps3fw==",
                "f0RdFRsg5jnVN7fZosJSb+mU1b1E+/0/S0OAeJ9vQVuOfw==",
                "fwctHn45zb6dC0KHcgIdjWYPF3saSv4wx5HvpWsJDYinfw==",
                "fxAgP9GkFmTTyOd+sco9m/HpUA7f5iEh2iMtpOabpFuQfw==",
                "f7eWoJkUCaboHEoqztba2uA2LvSLCftbSRmLtfPia16pfw==",
                "f1L41x62JMeW8df3L3C8IxwOBq2es3rmMjExvm5phZscfw==",
                "f+dzMnGyIzpi59lEaZURUkXq5WskoUoR+2VPG2sPUzI4fw==",
                "fxlGGPXuHgb4ctpAB5gyE617NjCKqLVArPszNdIRuAyRfw==",
                "fypD1Mp8Fha5Cz8U77/+kRELX5JAHcZ+NOpJVyvVUcoffw==",
                "fy7pZ/FIhj/Uw8KazDl6PEWY3hYhaUqor38dfUXUqyNNfw==",
                "f78ZSJv8jvfM1D/Kshn0yAbo4tBZDvx/lJyw+wTqnktBfw==",
                "f+7jzCCjZWW0vuBIhtRQgh415iMsMiREqaCr2Mey4iKwfw==",
                "fyYarBflmM2g2UJ+BhgK2rnmCykZZkWZKRnbwyUFmc20fw==",
                "f5srxFeXzQSwrWOJ4Ikg5nLchjAkV07SFbT4itvrjCHKfw==",
                "f+lsphIF+/7EeBQKNTJkQzA9ss7+HIOOuzcMCBQvN7zUfw==",
                "f7IIwLBuj3htQkZKLXH/O5TwgsTPxBRSbJZdLtNEcuryfw==",
                "fxqkJn+M2kVQoVf+O0/l2cbM3QGSqtuFARDSz6omVWEYfw==",
                "f038U1kfUObA0wYt0TD9kqFMqO4grGb8I7BXQ0XazHLHfw==",
                "f6VUm54SB7tl0Yhvcje8hXHGx7xZYEAwEONMdN40zVwVfw==",
                "f9AvrY8ZWjvuSsJ5X/qxXu5fPbG9QUCbIsWx2yX8ltGHfw==",
                "fxP8scgNmsV61kMxMoWk3MmTmFVycZLDMSnt0OCL1TjWfw==",
                "f/PFVjBOuQGoWznwKqN7XTW0NVMcWuFQuouZ9QZs8XcBfw==",
                "f6GADZHZG3VmPY70JUmuhyJOzkYMIN6Zd2Ca1ZG80mrFfw==",
                "f9ttQ/YP01WByuNH8I0gvSS6Je0F3IYE9zPWoJhFuADrfw==",
                "fzIsoXvVWFYBu5j63XbNV9KGYCmOlIw+akzhlKivwhs+fw==",
                "f91CzLphjys9fSTEHNM607DNjBQm3rF18LurvGtLS0Mkfw==",
                "f2zq+iGpVG22/PCXyS+NzV9QRVvt6uL/nxiaQlaKEEwRfw==",
                "f/LXvGKemBti3Pg+iF0lgEhtqybs0nE/wZQTlbmgqOO7fw==",
                "f5ecdW3GP8RO6LFFomHAfs6YwwDZ6eV2TosmDrlcvbk1fw==",
                "fzUUwxh7e/ieZf2O2DamrCm2j9REslc7hzDY+fZLV52vfw==",
                "fzDml/nwoL3rtZd/yj+7IqmD3/h8hwFMC6i6r6IFsRrGfw==",
                "f6cgSHLRe7DJFiVb2Xys6Dla3UGtGWHz36LQkNggPKa5fw==",
                "f3A5KYdMEaGqk8xCariXKxXJXPmJay1cEOO8qwj0Kyyufw==",
                "f0o0yAkVgLFvK+DaTP+ONjpytpYDpmS2Li7PIbEFpsgbfw==",
                "f9aZHQ+BylApZ7jvL6SSZynrMpS2LpBcGXWeGpR9nrEbfw==",
                "f9KJtANoZjnp+yytnvubxsW+xuQktQpeeZ9kPTLq7kqefw==",
                "f+YxFGmYgV/QY6YduYKEo2Jq5RnS6VjThNj5LrpZMEowfw==",
                "f1essLOjgjgkFm5QFDttpR2ZKqZ+jhjLBLzmjZ23jmynfw==",
                "f2Tgn8HR+UkTmnGm2VuItGzE8n0QqhRG62WvRhp9IDohfw==",
                "f+9CkGn1iTqpIAMANPW7aAQdd8mfoJGnGQ9+WOCgdDKGfw==",
                "f2kRE/7kESiTsbNLHZHasITToozRVH/cEAUQ81gGWfXUfw==",
                "f6AW2H7FRGtlWHXLMvEcddlzvMQ9w+FRzKAbmY43lF9Ufw==",
                "f3AR6bYX1DS1lH3hp+znmX8929CWBWBEYSXADv3gZVAKfw==",
                "f30in0Q7GXz2eu8Cl4vLuBCZWlN42IDlss8N1atOX422fw==",
                "f9SNwJsDrfGPicZrq955fgutl9/xdUSofec25zPO/V3Bfw==",
                "f6My5uDezEUnhzPRvYCJEmg7A4Ngb5frNPTlmCVZLnMsfw==",
                "f6m6zXzOaZcrHLXWTl2KhNDLbpBgWbmptN4WK46xLRnFfw==",
                "f5ZlxGfutrSMalRaG7w94jwG73pazKRoZzwBhWN9wwBVfw==",
                "fw5z9pD46fRnJoOF1t/jWaLSHMBSJA0zjwDCG0UohJJTfw==",
                "f0mds41SCwO+p2ij49ZhOWQ1voV+C/NNawnmyTzaczk5fw==",
                "f31ExkF7+IJxbtJ06IT+dxXe5OFsHRrlKkk/cXXpLyOWfw==",
                "f+j1/iamw+7uVwog5yltr7090gtD162AK3oyTRG3syyufw==",
                "f3XvaNrsdq8Rc/XVxXDGg0NG8J0LfFZdEM4Sx1pQ/WiGfw==",
                "f6ZvcgpvQ7KMdwtw8pmBk8iS1siCAHG+hlPyTxZegj0Wfw==",
                "fyZVNlWNhmrvmITwh9tFxQIg3EKKxeDNl4+3ZN+X0ZSefw==",
                "f4azJvnEa9MpMBDgYsCdu4lo90K2wvnHsbFWmxvnAWx8fw==",
                "f9I3mNUV/AAvZ+QkH7AE54kuWTb/cKonIQjxvGO9kiVmfw==",
                "f7S4xzr2wyqRim5jx+rhr03/BjTVJDvcGiyn+C7TMhpqfw==",
                "f0/9TVGmxhPM5JvrX4M0TSvSfLq7qJU2Dp3L839j5lNqfw==",
                "f7Zx/0fUdn+tcGWQPffcabwFAUodP3k/AgUFJ4PTCKKjfw==",
                "f8coIUlFdeZFRS/DoFH04FUaBoxyOVHnEADTnqq1Auapfw==",
                "f54u5o3UpBxD+7DosrhHuGZBskHOsrUhQYWOU4IZ/vNqfw==",
                "fxWpPSMCr3k9vhxcRK5jFP8ahAchwDhxNcl2vShIh7tHfw==",
                "f2FAPcyczSQTWPkvU2dKP3/8cx2RjQmEn5TU8YMFtkH8fw==",
                "f+7/19qwIbw6V2cdZlPeQY7lYfMoqmW0O3+HlR0q3QZkfw==",
                "f/w+WvKkMtVXv0AQ5nOZTQZF8UD9paSUHIkap9WmpJTcfw==",
                "fx9xxyXxkLbXudPK8PLuUkH8QIef2Yr5hpQpSRUKU09ffw==",
                "fz5jnjyG3rGlpdy8ru42Hr2vLMVU6r4BoLwpt1XR99B+fw==",
                "fy0F7A0ojLZGFnd7kmYpF2UrWKQ1BZXw5yhxLmM5xSzDfw==",
                "f/BSqfA/502pQALOG91Pdnb6rySN5uJunNEtRybF8ckTfw==",
                "f4aAzt7GtxxRPGEAlPOd/JGlH8roJgdt2TvcySZTQ1fBfw==",
                "f4T0LZWOeFwQuWODbxGUIPCmREKwj21ez8Z4yCDU+NFZfw==",
                "f7ZZ7gcLwGRiXf4ZIAcA+0XSAIEjdEmASLoWi6MT9+8ifw==",
                "f51+kBWsbXNQ1NSe1O8b7KVQ1jyyPrjlwOQxdpbogGfdfw==",
                "f+YEb18n2JqbkP1yd1dD5aESHN0uiZA3+Hp0Yh9jyWu4fw==",
                "f0I/J8QDFnuPE8oe740tFLgBsP9ZoKbNCYMuDgiOwPwTfw==",
                "fxhrYf6IkOMefdUUGOnsifPtcOC1wkAoJcvtm+41ifpDfw==",
                "f3/pZVwlI5hcQj9fq2vBwiGKm1x9NxU3ZAMVy0jeg3GSfw==",
                "f3KhPsJ48QH4iVunAGyRFCblx4lpqmoxwkZdGRxG9fGqfw==",
                "f1ca64cKwM0oMZ78frtN5Z+hpgbD52RcxHdjtxBBB6Nvfw==",
                "fxZuVecc+cuMjyOHz/e/OKZEeCND+SnsyqA0FXv4Fa6Pfw==",
                "f6NLKC1PVEHT//ihsCvBbwse9PT9Op+HcZhVLXRQt9c2fw==",
                "fxv1UdZudwpuYI+mahYnkeGRO4pz1d4iXgYKuu19wLdsfw==",
                "f9uaEx+e6ron78UliSj+RzO0jb93HNAx715RV+yQE16sfw==",
                "f+0Kr75pwASIAuXAhfTjOLPK6Vfw57uNb7QDA1S/JaRlfw=="
        };
        final List<String> pl = Arrays.asList(pans).subList(0, 10);

        // define Spark Context
        final SparkConf sparkConf = new SparkConf().setAppName("SparkHBaseTest").setMaster("local[16]");
        final JavaSparkContext jsc = new JavaSparkContext(sparkConf);

        // create connection with HBase
        Configuration config = null;
        try {
            config = HBaseConfiguration.create();
            config.set("hbase.zookeeper.quorum", "guest136.hadoop.jac,guest142.hadoop.jac,guest148.hadoop.jac");
            final String tableName = "tkn_vault_DEV";
            config.set("hbase.zookeeper.quorum", "guest136.hadoop.jac,guest142.hadoop.jac,guest148.hadoop.jac");
            config.set("zookeeper.znode.parent", "/hbase-unsecure");
            config.set("hbase.master", "guest138.hadoop.jac:16000");
            config.setInt("timeout", 120000);
            config.set("zookeeper.znode.parent", "/hbase-unsecure");
            config.set(TableInputFormat.INPUT_TABLE, tableName);
            //            config.set(TableInputFormat.SCAN_ROW_START, "startrowkey");
            //            config.set(TableInputFormat.SCAN_ROW_STOP, "stoprowkey");
            HBaseAdmin.checkHBaseAvailable(config);
            System.out.println("HBase is running!");
        }
        catch (final MasterNotRunningException e) {
            System.out.println("HBase is not running!");
            System.exit(1);
        }catch (final Exception ce){
            ce.printStackTrace();
        }

        config.set(TableInputFormat.INPUT_TABLE, "tkn_vault_DEV");
        // config.set(TableInputFormat.SCAN_COLUMN_FAMILY, "data"); // column family
        // config.set(TableInputFormat.SCAN_COLUMNS, "data:tkn data:sha"); // 3 column qualifiers
        // config.set(TableInputFormat.SCAN, value);


        final StringBuilder buf = new StringBuilder();
        pl.forEach(p-> {
            final Configuration config2 = HBaseConfiguration.create();
            config2.set("hbase.zookeeper.quorum", "guest136.hadoop.jac,guest142.hadoop.jac,guest148.hadoop.jac");
            final String tableName = "tkn_vault_DEV";
            config2.set("hbase.zookeeper.quorum", "guest136.hadoop.jac,guest142.hadoop.jac,guest148.hadoop.jac");
            config2.set("zookeeper.znode.parent", "/hbase-unsecure");
            config2.set("hbase.master", "guest138.hadoop.jac:16000");
            config2.setInt("timeout", 120000);
            config2.set("zookeeper.znode.parent", "/hbase-unsecure");
            config2.set(TableInputFormat.INPUT_TABLE, tableName);
            config2.set(TableInputFormat.SCAN_ROW_START, p);
            config2.set(TableInputFormat.SCAN_ROW_STOP, p);
            final JavaPairRDD<ImmutableBytesWritable, Result> hBaseRDD =
                    jsc.newAPIHadoopRDD(config2, TableInputFormat.class, ImmutableBytesWritable.class, Result.class);
            final JavaPairRDD<String, String> rowPairRDD = hBaseRDD.mapToPair(
                    new PairFunction<Tuple2<ImmutableBytesWritable, Result>, String, String>() {
                        /**
                         *
                         */
                        private static final long serialVersionUID = -1381144551765690004L;

                        @Override
                        public Tuple2<String, String> call(
                                final Tuple2<ImmutableBytesWritable, Result> entry) throws Exception {

                            final Result r = entry._2;
                            final String keyRow = Bytes.toString(r.getRow());
                            final String value =
                                    String.format("%s_%s",
                                            Bytes.toString(r.getValue(Bytes.toBytes("data"), Bytes.toBytes("tkn"))),
                                            Bytes.toString(r.getValue(Bytes.toBytes("data"), Bytes.toBytes("sha")))
                                            )
                                    ;
                            return new Tuple2<>(keyRow, value);
                        }
                    });
            final Tuple2<String, String> t = rowPairRDD.first();
            System.err.println("B ##################################################");
            System.err.println("# RESULT : " + p + " ... " + t.toString() );
            buf.append(t.toString()).append('\n');
            System.err.println("E ##################################################");

        });

        System.err.println(buf.toString());

        final JavaPairRDD<ImmutableBytesWritable, Result> hBaseRDD =
                jsc.newAPIHadoopRDD(config, TableInputFormat.class, ImmutableBytesWritable.class, Result.class);
        // in the rowPairRDD the key is hbase's row key, The Row is the hbase's Row data
        final JavaPairRDD<String, String> rowPairRDD = hBaseRDD.mapToPair(
                new PairFunction<Tuple2<ImmutableBytesWritable, Result>, String, String>() {
                    /**
                     *
                     */
                    private static final long serialVersionUID = 4396355635792347039L;

                    @Override
                    public Tuple2<String, String> call(
                            final Tuple2<ImmutableBytesWritable, Result> entry) throws Exception {

                        final Result r = entry._2;
                        final String keyRow = Bytes.toString(r.getRow());
                        final String value =
                                String.format("%s_%s",
                                        Bytes.toString(r.getValue(Bytes.toBytes("data"), Bytes.toBytes("tkn"))),
                                        Bytes.toString(r.getValue(Bytes.toBytes("data"), Bytes.toBytes("sha")))
                                        )
                                ;
                        // define java bean
                        //final TestData cd = new TestData();
                        // cd.setRowkey(keyRow);
                        // cd.setVc((String) Bytes.toString(r.getValue(Bytes.toBytes("cf1"), Bytes.toBytes("vc"))));
                        // cd.setVs((String) Bytes.toString(r.getValue(Bytes.toBytes("cf1"), Bytes.toBytes("vs"))));
                        return new Tuple2<>(keyRow, value);
                    }
                });
        //final Tuple2 t = rowPairRDD.first();
        rowPairRDD.lookup("fyvvC0/d3EthhdD/flkTY7N2f6Z8kvRWoIuMm6s6DV4kfw==").forEach(System.err::println);
        //        System.err.println("B ##################################################");
        //        System.err.println("# RESULT : " + t.toString() );
        //        System.err.println("E ##################################################");

        //System.err.println( rowPairRDD.count() );
        // final Tuple2 t = rowPairRDD.first();
        //        System.err.println("B ##################################################");
        //        System.err.println("# RESULT : " + t.toString() );
        //        System.err.println("E ##################################################");

        //        final String[] pans = {"f1unqJQ0r/ThsYHmrZldO5Mhnyt9Xq6WZQOMemPUVJyofw==",
        //                "f/3JOpMp93vURgeNp2YbkwkiMSV8pJHvQynLeLUHnDTNfw==",
        //                "f3mHbEDX/A2w4SFRDCIz4m20y0lmwcR4H19TjAVtwNBmfw==",
        //                "f8I5+r7ZDlosMaCNgs7L/vA5b9VwNwWor7PbvCerBGrbfw==",
        //        "fxpd/t8RMkcfGyB+XQA07ompw0hOZEiXZkMaJUIscOQ+fw=="};
        //        final List<String> pl = Arrays.asList(pans);
        //rowPairRDD.take(5).forEach(System.err::println);
        //pl.forEach( k->rowPairRDD.lookup(k).forEach(System.err::println) );
        // rowPairRDD.lookup(key)

        //        rowPairRDD = rowPairRDD.filter( new Function<Tuple2<String,String>, Boolean>() {
        //
        //            @Override
        //            public Boolean call(final Tuple2<String, String> tuple) throws Exception {
        //                final boolean b = pl.contains(tuple._1);
        //                if(b) {
        //                    System.err.println(tuple._1);
        //                }
        //                return b;
        //            }
        //        });

        //        System.err.println( "# FILTER COUNT : " + rowPairRDD.count() );

        jsc.close();

    }
}
